### ISSUE TITLE
  Process `handleSingleFile (1)`  and `pipeline:getVersions` terminated with an error exit status (127)

### ISSUE THREAD

**Issue by SergioMG97** [epi2me-labs/wf-metagenomics#10]
Hi, when  i run:

> `nextflow run epi2me-labs/wf-metagenomics/ --fastq /mnt/lustre/scratch/nlsas/home/csic/nmy/vgc/dataANDanalysis/analysis/16s/16s_initial_5samples/16s_quality_length_filter.fastq --threads 64 --source ncbi_16s_18s`

It raises the next error :

```
> Error executing process > 'pipeline:getVersions'
> 
> Caused by:
>   Process `pipeline:getVersions` terminated with an error exit status (127)
> 
> Command executed:
> 
>   python -c "import pysam; print(f'pysam,{pysam.__version__}')" >> versions.txt
>   python -c "import pandas; print(f'pandas,{pandas.__version__}')" >> versions.txt
>   fastcat --version | sed 's/^/fastcat,/' >> versions.txt
>   minimap2 --version | sed 's/^/minimap2,/' >> versions.txt
>   samtools --version | head -n 1 | sed 's/ /,/' >> versions.txt
>   taxonkit version | sed 's/ /,/' >> versions.txt
>   kraken2 --version | head -n 1 | sed 's/ version /,/' >> versions.txt
> 
> Command exit status:
>   127
> 
> Command output:
>   (empty)
> 
> Command error:
>   .command.run: line 279: docker: command not found
> 
> Work dir:
>   /mnt/netapp1/Store_CSIC/home/csic/nmy/vgc/metagenomics/nextflow/epi2me-labs/wf-metagenomics/work/7a/361c9fa3737593405
> 
> Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
> 
> 
```

I tryed with:

> `nextflow run epi2me-labs/wf-metagenomics/ --fastq /mnt/lustre/scratch/nls16s/16s_initial_5samples/16s_quality_length_filter.fastq --minimap2 --threads 64`

 But a  similar error appears:

```
> Error executing process > 'handleSingleFile (1)'
> 
> Caused by:
>   Process `handleSingleFile (1)` terminated with an error exit status (127)
> 
> Command executed:
> 
>   mkdir 16s_quality_length_filter
>   mv 16s_quality_length_filter.fastq 16s_quality_length_filter
> 
> Command exit status:
>   127
> 
> Command output:
>   (empty)
> 
> Command error:
>   .command.run: line 279: docker: command not found
> 
> Work dir:
>   /mnt/netapp1/Store_CSIC/home/csic/nmy/vgc/metagenomics/nextflow/epi2me-labs/wf-metagenomics/work/e5/75cd9ea0f88868016eabdd546378f8
> 
> Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
> 
> 
```

I tried with my own minimap reference and it raises the same
Im in a cluster, so i changed executor to slurm in nextflow.config as documentation in nextflow suggests, but it raises grid scheduler error. Lastly i have changed executor specifications to cpu=64 and ram to 64 GB in order to set the same specifications of the salloc which i ask for in the cluster. But the error doesnt change.
My nexflow version is 22.04.0

Do you figure out what could be happening?

Thank you in advanced
Best,
Sergio

**Comment by Karhide** [comment]
Hey Sergio,

Do you have docker installed in your environment?

**Comment by nggvs** [comment]
Hi,
Thank you for using the workflow. Could you confirm if this issue has been solved? We'll close this ticket on the assumption things are now resolved.
