### ISSUE TITLE
Fastq file format

### ISSUE THREAD

**Issue by RarltyOne** [epi2me-labs/wf-metagenomics#104]
### Operating System

Ubuntu 22.04

### Workflow Version

All workflows

### Workflow Execution

EPI2ME Desktop (Local)

### Workflow Execution - CLI Execution Profile

None

### What happened?

FastaQ format dont identified
![Снимок экрана от 2024-06-12 16-08-27](https://github.com/epi2me-labs/wf-metagenomics/assets/171215367/d2b042d5-b57f-4ec9-85b0-6d51b15d6436)

### Relevant log output

```shell
none
```

### Were you able to successfully run the latest version of the workflow with the demo data?

yes

**Comment by nggvs** [comment]
Hi @RarltyOne ,
the screenshot of the folder content is the one that pop up from the app and you mean that you cannot select the file? If that is the case, could you move the fq file to a folder and in EPI2ME load the folder (the wf will take any fq within that folder) and let me know if that works for you?

Thank you very much in advance!

**Comment by nggvs** [comment]
Hi @RarltyOne ,
Does this problem persists with the latest version of the [EPI2ME Desktop Application](https://labs.epi2me.io/downloads/) (5.2.0)?
Thank you for using the app and the workflows!

**Comment by nggvs** [comment]
Hi, I'm closing this issue, assuming it has been solved in the latest version, but please feel free to open a new one if you have any other problem.
Thank you very much!
