### ISSUE TITLE
Combining PlusPFP and EuPathDB46 databases and adding custom sequences

### ISSUE THREAD

**Issue by msubirana** [epi2me-labs/wf-metagenomics#105]
### Ask away!

Hi,

I am looking to combine the PlusPFP and EuPathDB46 databases (available at https://benlangmead.github.io/aws-indexes/k2) and add custom sequences to this combined database for use in a Nextflow pipeline. For combining PlusPFP and EuPathDB46, do I need to concatenate the tar files, or is there an alternative approach? Additionally, how should I proceed with incorporating custom sequences into this combined database?

Thank you for your assistance.

**Comment by cjw85** [comment]
To build a custom database you will need to follow the guide in linked at the bottom of the README:

https://github.com/epi2me-labs/wf-metagenomics#related-blog-posts
