### ISSUE TITLE
Turn off fastcat?

### ISSUE THREAD

**Issue by lucyintheskyzzz** [epi2me-labs/wf-metagenomics#109]
### Ask away!

Hi!  I am still trying to work out the kinks on running EPI2ME on HPC (need to get singularity permissions from admins), but I successfully ran some samples using our windows local lab computer:

Processor	13th Gen Intel(R) Core(TM) i9-13900K   3.00 GHz
Installed RAM	64.0 GB (63.7 GB usable)
Device ID	C6696543-8F4E-4704-BFE5-64831630A7E4
Product ID	00355-60979-80843-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
Edition	Windows 11 Pro
Version	23H2
Installed on	‎7/‎5/‎2023
OS build	22631.3593
Experience	Windows Feature Experience Pack 1000.22700.1003.0

The only thing is that my samples were all concatenated into one sample and separated out into separate barcodes. I think this is because I basecalled using Dorado on HPC and all my samples are already concatenated and in the same directory. I think maybe fastcat is concatenating all my barcodes together (maybe I am wrong). Is there a way to turn off fastcat on the Windows Epi2Me desktop and on command-line (when I get this up a running)? 

Here is how my samples are structured in the same folder: 
![image](https://github.com/epi2me-labs/wf-metagenomics/assets/71407498/deaa5ba9-0047-43ac-8af4-0db292c14285)

Thanks for your help!
KT

**Comment by nggvs** [comment]
Hi @lucyintheskyzzz ,

Thank you for trying the workflow! The input accepted by the workflow is:
```
(i)                     (ii)                 (iii)    
input_reads.fastq   ─── input_directory  ─── input_directory
                        ├── reads0.fastq     ├── barcode01
                        └── reads1.fastq     │   ├── reads0.fastq
                                             │   └── reads1.fastq
                                             ├── barcode02
                                             │   ├── reads0.fastq
                                             │   ├── reads1.fastq
                                             │   └── reads2.fastq
                                             └── barcode03
                                              └── reads0.fastq
```
you can take a look here in the README: https://github.com/epi2me-labs/wf-metagenomics?tab=readme-ov-file#input-example
If you don't want to concatenate the samples, they need to be in different barcode folders. All the FASTQ within a barcode or folder are concatenated.
Hope you find this useful!

**Comment by lucyintheskyzzz** [comment]
@nggvs thanks! I guess I didn't interpret "(i)" as being in separate folders. I will do that and re-run it and see what I get thanks for your help!

**Comment by nggvs** [comment]
Hi @lucyintheskyzzz ,
you would need to have one folder per barcode and within it the corresponding FASTQ of that sample. I'll close the issue as it seems to be answered, please feel free to open a new one if you find something unexpected.
Thank you very much for using the workflow!
