### ISSUE TITLE
Duration of the Analysis using Metagenomic - Kraken2 (Standard 8)

### ISSUE THREAD

**Issue by CurryMuthu** [epi2me-labs/wf-metagenomics#110]
### Ask away!

Hi, its my first time using Epi2me to analyze about 40-60 fastq files. Is it normal for the process to take more than 12 hours? I have tried to download the Kraken2 Database as a Reference File (tar.gz) and its going to take more than a day to download. Any advice to this? Thank you!

![Screenshot 2024-06-28 000013](https://github.com/epi2me-labs/wf-metagenomics/assets/145911163/6583e92b-daca-4f8b-8586-98e7466ecbbe)
![Screenshot 2024-06-27 235958](https://github.com/epi2me-labs/wf-metagenomics/assets/145911163/dea44d9a-cebf-44f3-afa8-d7573dfe6719)

**Comment by cjw85** [comment]
Please reopen your issue using the bug report issue template and provide the requested information.
