### ISSUE TITLE
Adding UNITE ITS database to the pre-built options

### ISSUE THREAD

**Issue by jdiazsupsi** [epi2me-labs/wf-metagenomics#115]
### Is your feature related to a problem?

The UNITE ITS [database](https://unite.ut.ee/index.php) has a different curation process than the NCBI `ncbi_16s_18s_28s_ITS` db. It would be very useful to be able to use it with wf-metagenomics.

### Describe the solution you'd like

Being able to run minimap2 selecting UNITE ITS as database (using the `--database_set` option in the workflow).

### Describe alternatives you've considered

Building myself the database. I tried following your [guide](https://labs.epi2me.io/how-to-meta-offline/#wandering-off-the-beaten-track) but it proved a bit difficult, since I use minimap2 and UNITE does not have a direct correspondence in its indices with NCBI. I did not manage to solve the issue of how to create of a working ref2taxid file. I still have to explore using Kraken to build the DB from scratch.

For now, I keep using the NCBI ITS database.

**Comment by nggvs** [comment]
Hi @jdiazsupsi ,
Thank you for your feedback! I'll add it to our possible additional features (or if it is not possible, I might write a blogpost). I agree that when the identifiers are not the NCBI one, creating a database could be a bit more difficult.
Thank you very much for using the workflow!

**Comment by jdiazsupsi** [comment]
Hi @nggvs, I came back to this task recently and I managed to run `wf-metagenomics` with Unite thanks to a script provided by a user in this [issue](https://github.com/DerrickWood/kraken2/issues/97#issuecomment-2437252980) of kraken2. If one uses this script to build the DB and then follows the instructions from the EPI2ME 'off-the beaten track' guide after the DB has been build (essentially only running the `bracken-build` and `generate_kmer_distribution.py` steps), it works as-is.

Sadly, I did not manage to get the `minimap2` pipeline running with the new database. There must be some difference of the `seqid2taxid.map` formatting that the step after minimap2 mapping fails to process. The file `${sample_id}.minimap2.assignments.tsv` results empty and throws this error:
```
  [11:53:24 - workflow_glue] Bootstrapping CLI.
  [M::mm_idx_gen::1.279*0.99] collected minimizers
  [M::mm_idx_gen::1.419*1.56] sorted minimizers
  [M::main::1.449*1.54] loaded/built the index for 93085 target sequence(s)
  [M::mm_mapopt_update::1.496*1.52] mid_occ = 619
  [M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 93085
  [M::mm_idx_stat::1.529*1.51] distinct minimizers: 2732412 (72.21% are singletons); average occurrences: 3.285; average spacing: 5.587; total length: 50147060
  [11:53:26 - workflow_glue] Starting entrypoint.
  Error: The reference 73746 is not found in your ref2taxid file.
                      Please make sure that the ref2taxid matches the reference.
                      If your input are bam files, make sure that the ref2taxid matches
                      the reference used for the mapping step.
```
The ref2taxid file contains the reference 73746 mentioned in the error, as well as the `library/unite.fna` file. Something happens in the `workflow-glue format_minimap2` step that 'breaks' the pipeline with my database. Do you have any idea of what may be going on here? 

Just for completion, I run the pipeline like this: 
```
nextflow run epi2me-labs/wf-metagenomics -profile singularity \
    --fastq $fq_filt --sample WA4 --out_dir $OUTDIR --threads 20 --classifier minimap2 \
    --taxonomy ${KRAKEN_DB}/taxonomy \
    --reference ${KRAKEN_DB}/library/unite.fna \
    --ref2taxid ${KRAKEN_DB}/seqid2taxid.map
``` 
Thanks a lot for developing the pipeline!

**Comment by ACJar** [comment]
Hello,
I am very new to bioinformatics and not super familiar with unix. I'm trying to build a UNITE database using the kraken2-unite-build.sh provided from the other post as well. When you ran the script what else did you have to specify? Is it the same as the kraken2-build command (ie kraken2-build --standard --threads 24 --db $DBNAME)?

Thanks!

**Comment by jdiazsupsi** [comment]
Hi @ACJar, nothing special, I just ran it like this: 
```
kraken2-unite-build.sh $db_dir $unite_fasta $threads
srun bracken-build -d $db_dir -l 1000
```

**Comment by ACJar** [comment]
Hi @jdiazsupsi thanks so much for replying! I was able to run the kraken2 script and bracken successfully!
