### ISSUE TITLE
Customize the workflow

### ISSUE THREAD

**Issue by Harper19** [epi2me-labs/wf-metagenomics#117]
### Is your feature related to a problem?

I would like to output some extra TSV files while generating the report.html in the default "output" folder. But currently, it can only be exported to the subfolder under "work". Cannot figure out which scripts related to mv from temp folder "work" to main "output" folder. 

### Describe the solution you'd like

It would be appreciated if which scripts I should modify. 

### Describe alternatives you've considered

The tsv files of align stats could be exported but cannot be exported to "output" folder.

**Comment by nggvs** [comment]
Hi @Harper19 ,
I have added this in our list to possible additional features, so I'll close the issue meanwhile.
You can modify the minimap.nf script but then may be more difficult to keep the workflow updated (you might have conflicts when updating)
Thank you for using the workflow!
