### ISSUE TITLE
Is it possible to access an index from a remote server using EPI2ME?

### ISSUE THREAD

**Issue by timregan** [epi2me-labs/wf-metagenomics#118]
### Ask away!

I'd like to use a very large [index](https://benlangmead.github.io/aws-indexes/k2) (nt, ~1 TB). 
This is too large to store locally on my latop, but I have plenty of space on a server. 

Can I set the directory for this large index on a remote server which I have access to using EPI2ME? 
Alternatively, are there any other options for using such a large index database?

Many thanks,

**Comment by cjw85** [comment]
The is possible in the real-time workflows with the port and host options, please see the README
