### ISSUE TITLE
AMR databases

### ISSUE THREAD

**Issue by rs-norman** [epi2me-labs/wf-metagenomics#120]
### Ask away!

Do the AMR databases used in the wf-metagenomics workflow need to be downloaded manually or are they part of the workflow install? I am not seeing any AMR databases in the epi2me workflow folders.

**Comment by nggvs** [comment]
Hi @rs-norman ,
the amr databases are included in the docker image for abricate so they are used when running the workflow, so you are not expected to see them in the workflow folder.
Thank you very much for using the pipeline!
