### ISSUE TITLE
custom viral database still results in bacteria/eukaryotes

### ISSUE THREAD

**Issue by katievigil** [epi2me-labs/wf-metagenomics#124]
### Ask away!

HI EPI2ME team,

I created a custom NCBI refseq viral database to run Kraken and it seems like I am still getting bacteria and eukaryote results. I am running this on a HPC.  I attached all my scripts and data so far. The workflow worked flawlessly, its just that I did not just get viruses in my output. Also, it looks like my sample_sheet.csv did not work to add the alias names to the output results. Let me know what you think?-I was thinking about trying minimap, but since I got kraken working, I thought there maybe a quick fix. 
[epi2me_nt.zip](https://github.com/user-attachments/files/18067437/epi2me_nt.zip)

I followed these directions: https://labs.epi2me.io/how-to-meta-offline/

nextflow run ~/workflows/wf-metagenomics/main.nf \
    --fastq /work/kvigil/onr.raw.data.sup.trim/rawdata/results/trimmed/fastq_all_raw \
    -profile singularity
    --exclude_host /work/kvigil/onr.raw.data.sup.trim/rawdata/results/trimmed/blanks/fastq/blanks_concatenated.fasta \
    --taxonomy /project/awlab/kvigil/scripts/epi2me/store_dir/viral_nucleotide/kraken2_database/taxonomy \
    --database /project/awlab/kvigil/scripts/epi2me/store_dir/viral_nucleotide/kraken2_database \
    --output_dir /work/kvigil/onr.raw.data.sup.trim/rawdata/results/trimmed/fastq_all_raw/kraken_nt_output \
    --sample_sheet /work/kvigil/onr.raw.data.sup.trim/rawdata/results/trimmed/epi2me_wf_metagenomics/sample_sheet.csv

Thanks!

**Comment by nggvs** [comment]
Hi @katievigil ,
Could you open this following the bug template? I've taken a quick look and seems that the database parameter you're providing is not being used. I have made a small try and I'm not able to reproduce it

**Comment by katievigil** [comment]
ok!

**Comment by katievigil** [comment]
Hi, I ended up switching to minimap.
