### ISSUE TITLE
[Bug]: kraken_pipeline.nf - kraken2_client could not get any data from kraken2_server when using a big kraken2 index

### ISSUE THREAD

**Issue by mlmpereira87** [epi2me-labs/wf-metagenomics#17]
### What happened?

On **kraken_pipeline.nf**, if the kraken index is big (example: nt), the kraken_server process do not have enough time to load de index and kraken_client process fails.

Solution:

Change ** kraken2_client process** like this:

```

process kraken2_client {
    errorStrategy { sleep(30000); return 'retry' }
    maxRetries 999
    label "wfmetagenomics"
    containerOptions {workflow.profile != "singularity" ? "--network host" : ""}
    maxForks 1 
    input:
        tuple val(sample_id), path(reads)
    output:
        tuple val(sample_id), path("*kraken2_report.txt"), path(reads), path("*.tsv")
    script:
    """
    kraken2_client --port $params.port --sequence "${reads}" > "${sample_id}.kraken2.assignments.tsv"
    kraken2_client --port $params.port --report --sequence "${reads}" > "out.txt"
    tail -n +2 "out.txt" > "tmp.txt"
    head -n -6 "tmp.txt"  > "${sample_id}.kraken2_report.txt"
    
    """

}

```

**errorStrategy** was set to retry every 30 sec. This avoid a lot of processes being started and failing during the kraken2 database loading, preventing the system to overload.

**maxRetries** was set to 999 to preven

### Operating System

ubuntu 20.04

### Workflow Execution

Command line

### Workflow Execution - EPI2ME Labs Versions

ontresearch/wf-metagenomics

### Workflow Execution - Execution Profile

Docker

### Workflow Version

v2.0.1

### Relevant log output

```shell
lost the logs because already solved the problem in my local repo. The pipeline failed in kraken2_client nextflow process telling that could not get any data from kraken2_server.
```

**Comment by cjw85** [comment]
This one was on the TODO list of things to improve.

I've this afternoon reworked the kraken2 server to asynchronously load the kraken2 database such that the gRPC server can respond to clients with an error code and tell them to wait until the server is ready to receive requests. We're going to rewrite the process to handle this specific error, rather than brute force the retry.

**Comment by cjw85** [comment]
@mlmpereira87 I believe this issue is now resolved.
