### ISSUE TITLE
[Bug]: --batch_size > 1 do not work

### ISSUE THREAD

**Issue by mlmpereira87** [epi2me-labs/wf-metagenomics#18]
Running in kraken2 mode with --batch_size > 1 is failling. I figured out that the error was due to an antire array with all fastq names being given to fastcat -x option (**kraken_pipeline.nf line 81**) instead of a multi argument, so I did this to the process **combineFilterFastq**:

```

process combineFilterFastq {
    label "wfmetagenomics"
    forks = params.threads.intdiv(6)*5 
    maxForks forks <= 0 ? 1 : forks
    cpus 1
    input:
        tuple val(sample_id), path(directory)
        path database
    output:
        tuple(
            val(sample_id),
            path("*.fastq.gz"),
            emit: filtered)
        tuple(
            val(sample_id),
            path("*.json"),
            emit: stats)
    shell:
    """
    A=\$(echo "${directory}" | sed 's/\\[//g' | sed 's/\\]//g' | sed 's/,//g')
    fastcat \
        -a "${params.min_len}" \
        -b "${params.max_len}" \
        -q 10 \
        -s "${sample_id}" \
        -r "${sample_id}.${task.index}.stats" \
        -x \$A | bgzip > "${sample_id}.${task.index}.fastq.gz"
    fastcat_histogram.py --file "${sample_id}.${task.index}.stats" --sample_id "$sample_id" 
    """
}


```
$A variable was created to remove the characters "[", "]" and "," and was given to -x. 

### Operating System

ubuntu 20.04

### Workflow Execution

Command line

### Workflow Execution - EPI2ME Labs Versions

ontresearch/wf-metagenomics

### Workflow Execution - Execution Profile

Docker

### Workflow Version

v2.0.1

### Relevant log output

```shell
the error message was from fastcat (lost the logs already) and was saying that the input fastq name was too long and printed an array of length = batch_size of fastq names.
```

**Comment by sarahjeeeze** [comment]
Hi @mlmpereira87, We have now updated this in the latest release.

**Comment by nggvs** [comment]
Hi,
Thank you for using the workflow. Could you confirm if this issue has been solved? I'll close this ticket on the assumption things are now resolved.

**Comment by nggvs** [comment]
Closing due to lack of response.
