### ISSUE TITLE
Permission issue

### ISSUE THREAD

**Issue by fgaudilliere** [epi2me-labs/wf-metagenomics#20]
### What happened?

I'm trying to run the workflow in command line, but I have an issue with docker permissions. I ran the following command:
`nextflow run epi2me-labs/wf-metagenomics --fastq test_data --kraken2`

### Operating System

ubuntu 18.04

### Workflow Execution

Command line

### Workflow Execution - Execution Profile

Docker

### Workflow Version

v2.0.1

### Relevant log output
```
Error executing process > 'kraken_pipeline:getVersions'

Caused by:
  Process `kraken_pipeline:getVersions` terminated with an error exit status (1)

Command executed:

  python -c "import pysam; print(f'pysam,{pysam.__version__}')" >> versions.txt
  python -c "import pandas; print(f'pandas,{pandas.__version__}')" >> versions.txt
  fastcat --version | sed 's/^/fastcat,/' >> versions.txt
  minimap2 --version | sed 's/^/minimap2,/' >> versions.txt
  samtools --version | head -n 1 | sed 's/ /,/' >> versions.txt
  taxonkit version | sed 's/ /,/' >> versions.txt
  kraken2 --version | head -n 1 | sed 's/ version /,/' >> versions.txt

Command exit status:
  1

Command output:
  (empty)

Command error:
  touch: cannot touch '.command.trace': Permission denied

Work dir:
  /home/gaudillf/wf-metagenomics/work/79/133b83bd3e5f4547948f1a8739a0f3

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
```

Apparently the error is similar to what is mentioned here: https://github.com/assemblerflow/flowcraft/issues/142
I tried the suggested fix, but it didn't work. Docker itself runs fine in command line (without sudo), so the permissions should be working...

**Comment by sarahjeeeze** [comment]
Hi, It does look like a docker permissions issue. Maybe check permissions, or try out the --singularity profile or have a look at https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user

**Comment by fgaudilliere** [comment]
Thanks!

I had already run `sudo usermod -aG docker $USER` after the docker install, but just to be sure I retried it and now I get a different error message:

```
Checking inputs.
[-        ] process > kraken_pipeline:unpackTaxonomy -
[-        ] process > kraken_pipeline:unpackDatabase -
[-        ] process > kraken_pipeline:kraken_server  -
No such variable: initial_items

 -- Check script '/home/gaudillf/.nextflow/assets/epi2me-labs/wf-metagenomics/./subworkflows/kraken_pipeline.nf' at line: 570 or see '.nextflow.log' file for more details
```

Line 570 of the kraken pipeline is `all_items = initial_items`, and here is the nextflow log entry:

[nextflow_log.txt](https://github.com/epi2me-labs/wf-metagenomics/files/10031669/nextflow_log.txt)

**Comment by sarahjeeeze** [comment]
Thanks! .. Is there another hidden file in the path where you ran the workflow from `.nextflow.log` .. that log attached I think is missing a few of the first lines?

**Comment by fgaudilliere** [comment]
Ah yes, sorry, I only copied the lines I thought were relevant to avoid sending too much useless info, but here is the full file from my latest attempt:
[nextflow.log](https://github.com/epi2me-labs/wf-metagenomics/files/10039612/nextflow.log)

**Comment by sarahjeeeze** [comment]
Looks like the project needs to be updated. I would just `nextflow drop epi2me-labs/wf-metagenomics` and then try to run it again.

**Comment by fgaudilliere** [comment]
I still get the error (the specified kraken pipeline line is not the same, but it's still related to the `initial_items`):

```
Checking inputs.
[-        ] process > kraken_pipeline:unpackTaxonomy -
[-        ] process > kraken_pipeline:unpackDatabase -
[-        ] process > kraken_pipeline:kraken_server  -
No such variable: initial_items

-- Check script '/home/gaudillf/.nextflow/assets/epi2me-labs/wf-metagenomics/./subworkflows/kraken_pipeline.nf' at line: 506 or see '.nextflow.log' file for more details
```
Here is the latest `.nextflow.log`
[nextflow.log](https://github.com/epi2me-labs/wf-metagenomics/files/10040009/nextflow.log)

**Comment by sarahjeeeze** [comment]
Thanks, I was able to recreate your error if i use a fastq filename that doesn't exist so maybe check wf-metagenomics/test_data is present in the directory you are running the cmd from. I will add a check if exists error there though.

**Comment by fgaudilliere** [comment]
The fastq.gz files exist, but they are in subdirectories (barcode1 and barcode2). I tried launching the command with `--fastq test_data/barcode1` instead, and it seems to be running! It's taking a while though, I'll let you know if it ends normally. 

Thanks for your help! :)

**Comment by sarahjeeeze** [comment]
Oh, I think your last cmd was `--fastq wf-metagenomices/test_data` maybe just `--fastq test_data` should work?

**Comment by fgaudilliere** [comment]
Ah, yes, you're right - sorry, that's a dumb mistake that I should have spotted myself ^^''
With that correction it all works like a charm on the whole test dataset! 

Thanks again :)

**Comment by sarahjeeeze** [comment]
We updated this in the latest release so it should give a more useful error message.
