### ISSUE TITLE
[Bug]: workflow fails when more 28 fastq files are being analyzed

### ISSUE THREAD

**Issue by jagos01** [epi2me-labs/wf-metagenomics#26]
### What happened?

The workflow aborts due to unexpected error when more than 28 fastq files are being analyzed.  I have avoided this by concatenating the files (>400) first and then running the workflow.   This workaround only works on post run analysis.  Real time analysis, with the --watch_path flag, fails on the 29th fastq file that is placed in the watch path. 

command:  
nextflow run epi2me-labs/wf-metagenomics --fastq /home/Desktop/Test_data_cat --out_dir /home/Data_Analysis/a_b_s/gsup_5.0.16/Analysis/BC_both_ends/wf-metagenomics/k2_pfp_16_BC18.29_v2.0.6_1 --database /home/Data_DB/Kraken2_db/k2_pluspfp_16gb_20220908

Error:
--------------------------------------------------------------------------------
This is epi2me-labs/wf-metagenomics v2.0.6-gf5d1e16.
--------------------------------------------------------------------------------
Checking inputs.
Checking custom kraken2 database exists
[-        ] process > kraken_pipeline:unpackTaxonomy -
executor >  local (3)
executor >  local (3)
executor >  local (3)
executor >  local (4)
executor >  local (4)
executor >  local (4)
executor >  local (4)
executor >  local (4)
executor >  local (4)
executor >  local (7)
executor >  local (7)
executor >  local (7)
executor >  local (8)
executor >  local (10)
executor >  local (10)
executor >  local (10)
executor >  local (13)
executor >  local (14)
executor >  local (14)
executor >  local (17)
executor >  local (17)
executor >  local (17)
executor >  local (17)
executor >  local (22)
executor >  local (22)
executor >  local (25)
executor >  local (25)
executor >  local (181)
[skipped  ] process > kraken_pipeline:unpackTaxonomy [100%] 1 of 1, stored: 1 ✔
[skipped  ] process > kraken_pipeline:unpackDatabase [100%] 1 of 1, stored: 1 ✔
[7b/f79621] process > kraken_pipeline:determine_b... [100%] 1 of 1 ✔
[8b/3864e5] process > kraken_pipeline:kraken_server  [100%] 1 of 1 ✔
[68/7222bf] process > kraken_pipeline:kraken2_cli... [100%] 30 of 30 ✔
[a8/db9b9b] process > kraken_pipeline:progressive... [100%] 30 of 30 ✔
[f0/0264b1] process > kraken_pipeline:progressive... [100%] 30 of 30 ✔
[d0/8682e0] process > kraken_pipeline:bracken (28)   [100%] 28 of 28
[52/116b2b] process > kraken_pipeline:getVersions    [100%] 1 of 1 ✔
[81/a91a62] process > kraken_pipeline:getParams      [100%] 1 of 1 ✔
[ee/a0a1b6] process > kraken_pipeline:makeReport ... [100%] 28 of 28
[2b/da7d81] process > kraken_pipeline:output (30)    [100%] 30 of 30
[a6/e59e7a] process > kraken_pipeline:stop_kraken... [100%] 1 of 1 ✔
Execution aborted due to an unexpected error

### Operating System

ubuntu 20.04

### Workflow Execution

Command line

### Workflow Execution - CLI Execution Profile

Docker

### Workflow Version

v2.0.6-gf5d1e16

### Relevant log output

```shell
none
```

**Comment by cjw85** [comment]
Hi @jagos01,

This is a known issue and will hopefully fixed this week.

**Comment by cjw85** [comment]
This should now be fixed with version v2.0.7
