### ISSUE TITLE
flag for sample_sheet does not work.

### ISSUE THREAD

**Issue by fwa93** [epi2me-labs/wf-metagenomics#27]
### What happened?

--Sample_sheet flag does not work. I get the workflow to work with a directory containing barcode directories but not when using a sample sheet. 
I have tried this on ubuntu and linux and I get the same error - "Missing process or function with name 'get_sample_sheet'"

edit: What format on the sample_sheet is expected from the pipeline? csv or tsv? Name of headers?

There also seem to be a problem with the --threads flag. When you try to use 8 or more than 8, the program crashes.

One last question: Which nextflow version do you reccomend for wf-metagenomics v.2.0.6?

### Operating System

ubuntu 20.04

### Workflow Execution

Command line

### Workflow Execution - EPI2ME Labs Versions

nextflow run epi2me-labs/wf-metagenomics -r v2.0.6 --fastq test_data/ -profile singularity  --sample_sheet sample_sheet.txt

### Workflow Execution - CLI Execution Profile

Singularity

### Workflow Version

v2.0.6

### Relevant log output

```shell
N E X T F L O W  ~  version 22.04.0
NOTE: Your local project version looks outdated - a different revision is available in the remote repository [a3a9d27cc2]
Launching `https://github.com/epi2me-labs/wf-metagenomics` [distracted_kalman] DSL2 - revision: f5d1e16131 [v2.0.6]
WARN: NEXTFLOW RECURSION IS A PREVIEW FEATURE - SYNTAX AND FUNCTIONALITY CAN CHANGE IN FUTURE RELEASE

||||||||||   _____ ____ ___ ____  __  __ _____      _       _
||||||||||  | ____|  _ \_ _|___ \|  \/  | ____|    | | __ _| |__  ___
|||||       |  _| | |_) | |  __) | |\/| |  _| _____| |/ _` | '_ \/ __|
|||||       | |___|  __/| | / __/| |  | | |__|_____| | (_| | |_) \__ \
||||||||||  |_____|_|  |___|_____|_|  |_|_____|    |_|\__,_|_.__/|___/
||||||||||  wf-metagenomics v2.0.6-gf5d1e16
--------------------------------------------------------------------------------
Core Nextflow options
  revision       : v2.0.6
  runName        : distracted_kalman
  containerEngine: singularity
  launchDir      : /aux/db/workdir_fwa010/wf-metagenomics
  workDir        : /aux/db/workdir_fwa010/wf-metagenomics/work
  projectDir     : /home/orebroll.se/fwa010/.nextflow/assets/epi2me-labs/wf-metagenomics
  userName       : fwa010
  profile        : singularity
  configFiles    : /home/orebroll.se/fwa010/.nextflow/assets/epi2me-labs/wf-metagenomics/nextflow.config, /aux/db/workdir_fwa010/wf-metagenomics/nextflow.config

Input Options
  fastq          : test_data/

Sample Options
  sample_sheet   : sample_sheet.csv

Reference Options
  database_sets  : [ncbi_16s_18s:[reference:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s/ncbi_targeted_loci_16s_18s.fna, refindex:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s/ncbi_targeted_loci_16s_18s.fna.fai, database:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s/ncbi_targeted_loci_kraken2.tar.gz, kmer_dist:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s/database1000mers.kmer_distrib, ref2taxid:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s/ref2taxid.targloci.tsv, taxonomy:https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz], ncbi_16s_18s_28s_ITS:[reference:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s_28s_ITS/ncbi_16s_18s_28s_ITS.fna, refindex:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s_28s_ITS/ncbi_16s_18s_28s_ITS.fna.fai, database:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s_28s_ITS/ncbi_16s_18s_28s_ITS_kraken2.tar.gz, kmer_dist:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s_28s_ITS/database1000mers.kmer_distrib, ref2taxid:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s_28s_ITS/ref2taxid.ncbi_16s_18s_28s_ITS.tsv, taxonomy:https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz], PlusPF-8:[database:https://genome-idx.s3.amazonaws.com/kraken/k2_pluspf_8gb_20210517.tar.gz, taxonomy:https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz]]

Other parameters
  process_label  : wfmetagenomics

!! Only displaying parameters that differ from the pipeline defaults !!
--------------------------------------------------------------------------------
If you use epi2me-labs/wf-metagenomics for your analysis please cite:

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x


--------------------------------------------------------------------------------
This is epi2me-labs/wf-metagenomics v2.0.6-gf5d1e16.
--------------------------------------------------------------------------------
Checking inputs.
[-        ] process > kraken_pipeline:unpackTaxonomy           -
[-        ] process > kraken_pipeline:unpackDatabase           -
[-        ] process > kraken_pipeline:determine_bracken_length -
[-        ] process > kraken_pipeline:kraken_server            -

Input directory assumed to be containing one or more directories containing fastq files.
Missing process or function with name 'get_sample_sheet'

 -- Check script '/home/orebroll.se/fwa010/.nextflow/assets/epi2me-labs/wf-metagenomics/main.nf' at line: 140 or see '.nextflow.log' file for more details
```

**Comment by cjw85** [comment]
Hi @fwa93,

I can reproduce you error that providing a sample sheet leads to the workflow stopping prematurely. I have raised an issue internally to fix this.

Can you provide more details on the crash when you specifiy more than 8 threads? My suspicion is that its not crashing per-se but that you are receiving an error that a job cannot be run because of a lack of resource? The default Nextflow configuration of the workflow is to allow up to 8 CPUs to be used. You can change this by specifiying an additional configuation file with:

```
nextflow run -c <config file> ...
```

with the contents:
```
executor {
    $local {
        cpus = <SOME NUMBER>
    }
}
```

**Comment by eparisis** [comment]
I just had the `--threads` error too. I used to run the workflow with `--threads 24`. Today I updated to the newest version and its not working anymore.

I get this error:
```
Error executing process > 'kraken_pipeline:kraken_server'

Caused by:
  Process requirement exceeds available CPUs -- req: 24; avail: 8

Command executed:

  # we add one to requests to allow for stop signal
  kraken2_server         --max-requests 24 --port 8080         --db ./database_dir/

Command exit status:
  -

Command output:
  (empty)

Work dir:
  /home/DNAdminseq/dnasqdatadrive/Projects/dnaseq/metagenomics/themis/wf-metagenomics/test/work/47/9e8d5b49c0e805e6118350506b106d

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
```

I also have a bit unrelated question. Everytime I try to rerun the same sample (for example if it got stuck due to an error) I always need to delete the trace.txt file in the output/execution folder. Is this how its supposed to be or is there a workaround?

**Comment by cjw85** [comment]
@fwa93, the help text of the `--threads` option reads:

>For the real-time kraken2 workflow, this is the number of CPU threads used by the kraken2 server (and the number of clients sending reads to the server). For the minimap2 workflow, it is the number of CPU threads used by minimap2. For the real-time kraken2 workflow the `threads` parameter should not be set to no more than 4 fewer than the executor CPU limit.

In you example it looks like you did not abide by the last sentence and `--threads` was set to the same value as `cpus` in your configuration file. I would actually recommend setting `--threads` to half the executor `cpu` setting as nextflow needs to schedule one kraken_client job for every simultaneous job the kraken server can handle.

**Comment by cjw85** [comment]
@fwa93 Apologies, you are correct, on the CLI only the short "description" help is shown rather than the full "help_text". There is currently no way to have these extending messages shown.
