### ISSUE TITLE
Implement memory-mapping kraken2 option

### ISSUE THREAD

**Issue by cjw85** [epi2me-labs/wf-metagenomics#29]
Thanks for the --max_len flag.  I will try it this evening.  I tried the workflow with the test data on my other computer (Ubuntu 18.04).  The default database works fine when using v2.0.1 and .  However, the k2_pluspfp database fails with the following error:

[97/0c13a6] NOTE: Process `kraken_pipeline:kraken2_client (1)` terminated with an error exit status (74) -- Execution is retried (1)
[13/2d19cb] NOTE: Process `kraken_pipeline:kraken2_client (2)` terminated with an error exit status (74) -- Execution is retried (1)
[87/9b2678] NOTE: Process `kraken_pipeline:kraken2_client (3)` terminated with an error exit status (74) -- Execution is retried (1)
[72/37b781] NOTE: Process `kraken_pipeline:kraken2_client (4)` terminated with an error exit status (74) -- Execution is retried (1)
Error executing process > 'kraken_pipeline:kraken2_client (1)'

Caused by:
  Process `kraken_pipeline:kraken2_client (1)` terminated with an error exit status (74)

Command executed:

  kraken2_client --port 8080 --sequence "barcode02.4.fastq.gz" > "barcode02.kraken2.assignments.tsv"
  kraken2_client --port 8080 --report --sequence "barcode02.4.fastq.gz" > "out.txt"
  tail -n +2 "out.txt" > "tmp.txt"
  head -n -6 "tmp.txt"  > "barcode02.kraken2_report.txt"

The kraken_server was not running during this workflow.  .command.log for the kraken_server process gave the following error:

Failed attempt to allocate 138245098056bytes;
you may not have enough free memory to load this database.
If your computer has enough RAM, perhaps reducing memory usage from
other programs could help you load this database?
kraken2_server: unable to allocate hash table memory   

Is there a way to avoid loading the database into RAM as I only have 126 available RAM on this computer?  Can --memory_mapping flag from kraken2 be implemented?

I also was able to verify that v2.0.3 behaves the same (one exception) as v2.0.1.  It completes with the default database and fails (runs out of memory) with the k2_pluspfp database.  The issues I was having with v2.0.3 are a result of store_dir.  If this folder exists, a new database is not used (even when a different one is specified) for the workflow.  So if I delete store_dir and run the workflow with the default database everything is fine.  If I then run again with k2_pluspfp database, without deleting store_dir, the workflow completes but the database in store_dir has not changed.  If I do the same but start with k2_pluspfp database both will fail because the k2_pluspfp database is used for both.

Thanks and I will try the --max-len flag tonight.  
Scott

_Originally posted by @jagos01 in https://github.com/epi2me-labs/wf-metagenomics/issues/22#issuecomment-1324357254_

**Comment by nggvs** [comment]
The `--memory_mapping` for kraken2 has been added in the latest release 2.3.0. To run this option, you should use the option `--kraken2_memory_mapping`.
