### ISSUE TITLE
[Bug]: `--threads` option triggers a bug

### ISSUE THREAD

**Issue by thecorz** [epi2me-labs/wf-metagenomics#35]
### What happened?

I'm running the pipeline using Nextflow CLI. When I specify a number of threads other than the default using the `--threads` option, I notice kraken2_server is not able to start. But if I don't change the number of threads then `kraken2_server` starts without problems. 

Until now, my workaround has been to start the server in a separate shell, but I just noticed that if I don't change the number of threads `kraken2_server` works just fine!

### Operating System

ubuntu 20.04

### Workflow Execution

Command line

### Workflow Execution - CLI Execution Profile

Docker

### Workflow Version

2.0.8

### Relevant log output

```shell
Connecting to server: localhost:8080.
Classifying sequence stream.
Server is not ready: failed to connect to all addresses
Waiting 10s...
Server is not ready: failed to connect to all addresses
Waiting 10s...
Server is not ready: failed to connect to all addresses
Waiting 10s...
Server is not ready: failed to connect to all addresses
Waiting 10s...
Server is not ready: failed to connect to all addresses
Waiting 10s...
Server is not ready: failed to connect to all addresses
Waiting 10s...
```

**Comment by sarahjeeeze** [comment]
Hi, what number are you using for threads? Note in the help text for threads it mentions ``` `threads` parameter should not be set to no more than 4 fewer than the executor CPU limit.``` So this would be 4 as the config executor is set to 8 - If you want to increase then you will also need to increase the executor CPU's.

**Comment by nggvs** [comment]
Hi,
Thank you for using the workflow. Could you confirm if this issue has been solved? I'll close this ticket on the assumption things are now resolved. Please feel free to open again if you are still having problems.

**Comment by nggvs** [comment]
Closing due to lack of response.
