### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by R11623009** [epi2me-labs/wf-metagenomics#37]
### What happened?

I ran the workflow of wf-metagenomics on epi2melabs in ubuntu 22.04.

I encountered a permission issue: `touch: cannot touch '.command.trace': Permission denied`

I had already run `sudo usermod -aG docker $USER` after installing docker and checked it can work without sudo.

I'm new to coding, so I'd tried my best to understand this issue beforehand.

I found out that adding `docker.runOptions = '-u $(id -u):$(id -g)'` in the nextflow.config seemed to solve this problem.
However, I saw a similar code in the nextflow.config. But I'm not sure whether that code helped, so I added  `docker.runOptions = '-u $(id -u):$(id -g)'`  in nextflow.config anyways, but it still didn't work.
Even I remove what I added, it still didn't work.

I also tried to run the docker image directly, but it exited immediately, (I'm not sure whether this information was helpful or not.)

Additionally, since I ran barcoded samples, I tried to run each barcode individually trying to circumvent the potential problem of "too much data", but of course, it still didn't work.

What should I do to solve this permission problem? Or there were other issues that I didn't aware of?

Thanks in advance.

### Operating System

ubuntu 20.04

### Workflow Execution

EPI2ME Labs desktop application

### Workflow Execution - CLI Execution Profile

None

### Workflow Version

2.0.8

### Relevant log output

```shell
Error executing process > 'kraken_pipeline:getParams'
Caused by:
  Process `kraken_pipeline:getParams` terminated with an error exit status (1)
Command executed:
  # Output nextflow params object to JSON
      echo '{
      "help": false,
      "version": false,
      "fastq": "/media/ac307/R111/R11623009/nanopore/16S_1_fastq_pass/barcode01",
      "sample": null,
      "sample_sheet": null,
      "max_len": null,
      "min_len": 0,
      "taxonomy": null,
      "classifier": "kraken2",
      "reference": null,
      "ref2taxid": null,
      "minimap2filter": null,
      "minimap2exclude": false,
      "split_prefix": false,
      "database": null,
      "bracken_dist": null,
      "bracken_length": null,
      "bracken_level": "S",
      "out_dir": "/home/ac307/epi2melabs/instances/wf-metagenomics_538a4fd5-1e07-4eaf-8b3f-29d6477ccf14/output",
      "wfversion": "v2.0.8",
      "disable_ping": false,
      "threads": 2,
      "aws_image_prefix": null,
      "aws_queue": null,
      "batch_size": 0,
      "watch_path": false,
      "store_dir": "store_dir",
      "read_limit": null,
      "port": 8080,
      "database_set": "ncbi_16s_18s",
      "database_sets": {
          "ncbi_16s_18s": {
              "reference": "https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s/ncbi_targeted_loci_16s_18s.fna",
              "refindex": "https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s/ncbi_targeted_loci_16s_18s.fna.fai",
              "database": "https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s/ncbi_targeted_loci_kraken2.tar.gz",
              "kmer_dist": "https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s/database1000mers.kmer_distrib",
              "ref2taxid": "https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s/ref2taxid.targloci.tsv",
              "taxonomy": "https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz"
          },
          "ncbi_16s_18s_28s_ITS": {
              "reference": "https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s_28s_ITS/ncbi_16s_18s_28s_ITS.fna",
              "refindex": "https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s_28s_ITS/ncbi_16s_18s_28s_ITS.fna.fai",
              "database": "https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s_28s_ITS/ncbi_16s_18s_28s_ITS_kraken2.tar.gz",
              "kmer_dist": "https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s_28s_ITS/database1000mers.kmer_distrib",
              "ref2taxid": "https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s_28s_ITS/ref2taxid.ncbi_16s_18s_28s_ITS.tsv",
              "taxonomy": "https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz"
          },
          "PlusPF-8": {
              "database": "https://genome-idx.s3.amazonaws.com/kraken/k2_pluspf_8gb_20210517.tar.gz",
              "taxonomy": "https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz"
          }
      },
      "process_label": "wfmetagenomics",
      "monochrome_logs": false,
      "validate_params": true,
      "show_hidden_params": false,
      "analyse_unclassified": false,
      "schema_ignore_params": "show_hidden_params,validate_params,monochrome_logs,aws_queue,aws_image_prefix,pangolin_version,wfversion,wf,process_label",
      "wf": {
          "example_cmd": [
              "--fastq test_data/barcode01/reads.fastq.gz"
          ],
          "agent": null,
          "container_sha": "sha156f44a25dd22e39eb10e82d12e0584d41dde909"
      },
      "wf.agent": "epi2melabs/4.1.1"
  }' > params.json
Command exit status:
  1
Command output:
  (empty)
Command error:
  touch: cannot touch '.command.trace': Permission denied
Work dir:
  /home/ac307/epi2melabs/instances/wf-metagenomics_538a4fd5-1e07-4eaf-8b3f-29d6477ccf14/work/31/0a716a95c0dd9dd801bd5e068313ba
Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
WARN: To render the execution DAG in the required format it is required to install Graphviz -- See http://www.graphviz.org for more info.
```

**Comment by sarahjeeeze** [comment]
Hi, Was docker installed on your computer by an administrator? Also perhaps try pasting the `docker.runOptions = '-u $(id -u):$(id -g)'` cmd in to the form in EPI2MELabs under extra configuration > configuration.

**Comment by R11623009** [comment]
I've checked that I installed docker as admin. 
I also pasted the cmd in extra configuration  > configuration. It still didn't work.
I tried reinstalling docker desktop and Epi2melabs again as admin, but it still show this message.

I forgot to mention that my computer has dual OS: windows and ubuntu 22.04 LTS.
Is there something to do with the dual OS?

**Comment by sarahjeeeze** [comment]
Is the default user in Ubuntu root?

**Comment by MetaGJezzy** [comment]
Hi!  I am getting the same error.  Have you found a solution yet?  If so, can you please share?

**Comment by R11623009** [comment]
I'd tried this way, and it worked eventually.
Prerequisite: I converted to single OS: ubuntu22.04 LTS.
First, check the docker daemon is running by execute cmd `sudo systemctl status docker`
Then, check if the user is the member using cmd  `groups`. If not, execute `sudo usermod -aG docker $USER`. Log out and log in again for the group memebership to take effect.
Next, check the permission of the docker socket: `ls -l /var/run/docker.sock` (The docker daemon need to be running to make this file exist)
If the permissions aren't set to "rw" for the user and group, change them using cmd `sudo chmod o+rw /var/run/docker.sock`.
And then, check the permissions of the docker directory using cmd `ls -ld /var/lib/docker`
If the permissions aren't set to "rwxr-xr-x", change them using  cmd `sudo chmod 755 /var/lib/docker`

After making these changes, the permission problem should be resolved, at least in my case.
