### ISSUE TITLE
[Bug]: Automatic finding of barcoded files not working when using minimap2 classifier

### ISSUE THREAD

**Issue by claczny** [epi2me-labs/wf-metagenomics#38]
### What happened?

This bug is linked to specifying a directory which holds directories which hold `fastq(.gz)` files, as an argument. It is not an issue when specifying a full path to a `fastq(.gz)` file.

The folder structure is
```
> ls -1 guppy_barcoder/
barcode01
barcode02
barcode03
barcode04
barcode06
barcode07
barcode08
barcode09
barcode10
barcode11
barcode12
barcode13
barcode14
barcode15
barcode16
barcode17
barcode18
barcode19
barcode20
barcode21
barcoding_summary.txt
guppy_barcoder-core-dump-db
guppy_barcoder_log-2023-02-16_09-45-02.log
unclassified
> ls -1 guppy_barcoder/barcode01 | head
fastq_runid_72506084f08d36ab1768237c543c2d96290fe7d9_0.fastq.gz
fastq_runid_72506084f08d36ab1768237c543c2d96290fe7d9_10.fastq.gz
fastq_runid_72506084f08d36ab1768237c543c2d96290fe7d9_11.fastq.gz
fastq_runid_72506084f08d36ab1768237c543c2d96290fe7d9_12.fastq.gz
fastq_runid_72506084f08d36ab1768237c543c2d96290fe7d9_13.fastq.gz
fastq_runid_72506084f08d36ab1768237c543c2d96290fe7d9_14.fastq.gz
fastq_runid_72506084f08d36ab1768237c543c2d96290fe7d9_15.fastq.gz
fastq_runid_72506084f08d36ab1768237c543c2d96290fe7d9_16.fastq.gz
fastq_runid_72506084f08d36ab1768237c543c2d96290fe7d9_17.fastq.gz
fastq_runid_72506084f08d36ab1768237c543c2d96290fe7d9_18.fastq.gz
```

When I run
```
./nextflow run epi2me-labs/wf-metagenomics -profile singularity --out_dir all_bcs_minimap2 --fastq $PREFIX/guppy_barcoder/ --classifier minimap2 # ${PREFIX} is some path
```
on our HPC (https://hpc.uni.lu; Rocky Linux 8.7 (Green Obsidian)), the workflow is unable to identify the `fastq.gz` files, i.e., it exits with `None of the directories given contain .fastq(.gz) files.`

In contrast, when I use the `kraken2` classifier, with
```
./nextflow run epi2me-labs/wf-metagenomics -profile singularity --out_dir all_bcs_minimap2 --fastq $PREFIX/guppy_barcoder/ --classifier kraken2 # ${PREFIX} is some path
```

It works fine and the HTML report nicely aggregates the read counts by barcode, just as in https://labs.epi2me.io/workflows/wf-metagenomics-report.html.

I thus had a bit of a look but as this is the very first time I am dealing with `nextflow`, I might have missed something.
In the `fastqingress` code, specifically https://github.com/epi2me-labs/wf-metagenomics/blob/af0af1bd25880b7eeedaf4486489a697ef923763/lib/fastqingress.nf#L177, the value of the second parameter of the `find_fastq` call is `false`. However, that prohibits it from descending one further folder, i.e., into the individual barcode folders to find the `fastq.gz` files there (output from `guppy_barcoder`).
So `search_subdirs` is `false` at https://github.com/epi2me-labs/wf-metagenomics/blob/af0af1bd25880b7eeedaf4486489a697ef923763/lib/fastqingress.nf#L100 and `files` is thus not filled with `fastq.gz` files.

Due to the real-time watch functionality that is exclusive to the `kraken2` classifier, it seems that this is differently solved for `kraken2`, but I did not understand how.

Either way, is this indeed a bug?
If so, how could this be fixed?

Thanks a lot!

Best wishes and stay safe,

Cedric 

P.S. I actually have to specify also a `--port`, e.g., 9123, when running the `kraken2` classifier as the default port 8080 is not available. This was killing the `kraken2_server` but I could not find a message in the `.nextflow.log`. Only by installing it via `mamba` and trying to run it manually, I received error messages that the port was already in use.
This might be relevant for other where it seems that the `kraken2` classification is stalled.
I omitted the `--port 9123` argument here for the sake of simplicity. 

### Operating System

ubuntu 20.04

### Workflow Execution

Command line

### Workflow Execution - CLI Execution Profile

Singularity

### Workflow Version

v2.0.8-g3e8fdcd.

### Relevant log output

```shell
Output Options
  out_dir        : all_bcs_minimap2

Advanced Options
  threads        : 12

Other parameters
  process_label  : wfmetagenomics

!! Only displaying parameters that differ from the pipeline defaults !!
--------------------------------------------------------------------------------
If you use epi2me-labs/wf-metagenomics for your analysis please cite:

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x


--------------------------------------------------------------------------------
This is epi2me-labs/wf-metagenomics v2.0.8-g3e8fdcd.
--------------------------------------------------------------------------------
Checking inputs.
Checking fastq input.
Barcoded directories detected.
Non barcoded directories detected.
None of the directories given contain .fastq(.gz) files.
```

**Comment by cjw85** [comment]
Hi Cedric,

The minimap2 route is scheduled for removal from the code.

It was originally intended to be used as a post processing step to kraken2, then got upgraded as a complete alternative, and then forgotten about and started to rot.

**Comment by cjw85** [comment]
Actually, apparently we have a branch where we've resurrected the minimap2 route! 😄 We'll assess how much effort it is for us to maintain both and perhaps resurrect it in the next release.

To address your point about the port. That looks like something where we need to improve the error reporting.
