### ISSUE TITLE
[Bug]: No output file with classified and unclassified reads

### ISSUE THREAD

**Issue by mbdabrowska1** [epi2me-labs/wf-metagenomics#39]
### What happened?

In the previous pipeline version (for example v1.1.0) one of the outputs was a classified reads fastq file with details about classification of each read. Is it possible to retain this feature as it is very useful for downstream analysis or at least make it optional if by default you are trying to avoid large data accumulation?

This refers to --classified-out option in kaken2 

### Operating System

ubuntu 20.04

### Workflow Execution

Command line

### Workflow Execution - CLI Execution Profile

Singularity

### Workflow Version

2.0.8

### Relevant log output

```shell
not relevant
```

**Comment by sarahjeeeze** [comment]
Thanks for your feedback, we will potentially add it back. But in the meantime you could maybe use [kraken tools - extract kraken reads](https://github.com/jenniferlu717/KrakenTools#extract_kraken_readspy)

**Comment by sarahjeeeze** [comment]
Closing for now as we won't be adding this in the near future but thanks for the feedback we may consider it in the future.

**Comment by nggvs** [comment]
Hi @mbdabrowska1! We have included these reports in the version 2.5.0. Yu should use the `--include_kraken2_assignments` and a TSV per sample with the classification per read will be generated within a folder called `kraken_reads_assignments`.
