### ISSUE TITLE
Workflow fails when using test data

### ISSUE THREAD

**Issue by seppinho** [epi2me-labs/wf-metagenomics#4]
Hi,
I tried to call the pipeline using the testdata:

` nextflow run main.nf --fastq test_data/reads.fastq.gz`

This is the error I get:

`* --sources: expected type: JSONObject, found: String ([TARGLOCI:[reference:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-ribosomal-survey/targeted_loci/ncbi_targeted_loci_16s_18s.fna, refindex:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-ribosomal-survey/targeted_loci/ncbi_targeted_loci_16s_18s.fna.fai, database:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-ribosomal-survey/targeted_loci/ncbi_targeted_loci_kraken2.tar.gz, kmer_dist:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-ribosomal-survey/targeted_loci/database1000mers.kmer_distrib, ref2taxid:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-ribosomal-survey/targeted_loci/ref2taxid.targloci.tsv, taxonomy:https://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz]])`

**Comment by sarahjeeeze** [comment]
Hi, I think you may need to update your nextflow version to  >= `21.10.6` you can do this using `nextflow self-update`.
