### ISSUE TITLE
[Bug]:  Include ".kraken2.assignments.tsv" in the output folder.

### ISSUE THREAD

**Issue by eparisis** [epi2me-labs/wf-metagenomics#41]
### What happened?

I was wondering if there is a way to add the `.kraken2.assignments.tsv` to the outputs since its very useful for downstream processing. 

I'm relatively new to nextflow and I was wondering if there is a way to add the `${sample_id}.kraken2.assignments.tsv` which is generated in the `kraken2_client` process with the `publishDir` function. 

If I try adding to the process outputs `path "${sample_id}.kraken2.assignments.tsv"` and `publishDir path: "${params.out_dir}", mode: 'copy', pattern:  "${sample_id}.kraken2.assignments.tsv", saveAs: {name -> "kraken"}, overwrite: true` to the process I get following error:
```bash
Invalid method invocation `call` with arguments: [barcode01, ../work/ee/00291fe5954f130ec83c0ce60706a9/barcode01.kraken2.report.txt, ../work/ee/00291fe5954f130ec83c0ce60706a9/barcode01.2.json, ../work/ee/00291fe5954f130ec83c0ce60706a9/barcode01.kraken2.assignments.tsv] (java.util.ArrayList) on _closure65 type
```
Any suggestions to make it work?

### Operating System

ubuntu 20.04

### Workflow Execution

Command line

### Workflow Execution - CLI Execution Profile

Docker

### Workflow Version

Latest

### Relevant log output

```shell
-
```

**Comment by sarahjeeeze** [comment]
Thanks for your feedback, we will potentially add it back. But in the meantime you could maybe use [kraken tools - extract kraken reads](https://github.com/jenniferlu717/KrakenTools#extract_kraken_readspy)

**Comment by sarahjeeeze** [comment]
Hi, thanks for the feedback we will consider adding it. In the meantime to implement it yourself, the above should work but only if you have one sample file per barcode as otherwise it will overwrite it with per file results or complain. You will need to add `path "${meta["alias"]}.kraken2.assignments.tsv"` to the outputs of the kraken2_client process. You will then need to replace any instances of `kraken2_client.out` with `kraken2_client.out[0]`

**Comment by eparisis** [comment]
Hi there, thanks for the reply. I will try that out. I noticed that for each file in a barcode, a separate `tsv` file is created but with the same name so they will indeed get overwritten. 

I also noticed that when I run the workflow for multiple runs from the same work directory I could only find the `tsv` files for the first run but not for the others in the work directories. Do you know anything about that?

I've seen that in your previous reply you mentioned Kraken-tools. That's one thing I need that file for. Krakentools uses the report of the read mappings which is this `.tsv` file. Would be nice if that file could be added to the pipeline outputs!

**Comment by sarahjeeeze** [comment]
Thanks for the feedback, we may consider adding it in the future but am closing for now as we won't be adding it in the near future.

**Comment by eparisis** [comment]
This will help a lot, thanks!
