### ISSUE TITLE
[Bug]: How to specify Bracken length

### ISSUE THREAD

**Issue by jackwgoodall** [epi2me-labs/wf-metagenomics#44]
### What happened?

Please can I ask how you suggest choosing the read length option for Bracken? 
Bracken itself wants a set read length - and obviously with nanopore the read lengths vary considerably. 
It seems that this is a live issue with the Bracken development team: https://github.com/jenniferlu717/Bracken/issues/60

It seems that a minimum read length might be the safest option? 

Many thanks,

Jack

### Operating System

ubuntu 18.04

### Workflow Execution

Command line

### Workflow Execution - CLI Execution Profile

Singularity

### Workflow Version

v2.0.8-g3e8fdcd

### Relevant log output

```shell
na
```

**Comment by cjw85** [comment]
I believe @nggvs has performed some research into this and found the results of the analysis to be fairly insensitive to the given length.
