### ISSUE TITLE
[ETC]: Implanting BLAST instead minimap2 in wf-metagenomics pipeline. 

### ISSUE THREAD

**Issue by pDestiny** [epi2me-labs/wf-metagenomics#45]
### What happened?

Hi.

I'm trying to replace minimap2 to BLAST instead of minimap2 in the wf-metagenomics pipeline.

I looked through the whole code(Started project one day before.), but It's difficult to understand quickly;especially the starting point to implant _blast_ tool.

I need recommendations about specific point of code to revise. 

I know the question is too naive and ambiguous. So, I expect to get detailed from an ambiguous answer.

### Operating System

ubuntu 20.04

### Workflow Execution

Command line

### Workflow Execution - EPI2ME Labs Versions

v2.2.1-g5344ddc

### Workflow Execution - CLI Execution Profile

Docker

### Workflow Version

23.04.1

### Relevant log output

```shell
No output. The purpose of this issue is for revision of the code
```

**Comment by nggvs** [comment]
Hi, thank you for considering the pipeline.
The starting point would be to replace the minimap process, but I'm afraid that also subsequent process would be affected as they would expect a different input. We'll take note on this to contemplate implementing it in future releases.
