### ISSUE TITLE
ERROR: Validation of pipeline parameters failed!

### ISSUE THREAD

**Issue by hpf0815** [epi2me-labs/wf-metagenomics#5]
Hi,

when I wanted to test the metagenomics workflow, I received following error message:

ERROR: Validation of pipeline parameters failed!
* --sources: expected type: JSONObject, found: String ([TARGLOCI:[reference:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-ribosomal-survey/targeted_loci/ncbi_targeted_loci_16s_18s.fna, refindex:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-ribosomal-survey/targeted_loci/ncbi_targeted_loci_16s_18s.fna.fai, database:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-ribosomal-survey/targeted_loci/ncbi_targeted_loci_kraken2.tar.gz, kmer_dist:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-ribosomal-survey/targeted_loci/database1000mers.kmer_distrib, ref2taxid:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-ribosomal-survey/targeted_loci/ref2taxid.targloci.tsv, taxonomy:https://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz]])

One of the commands I used was the following:

nextflow run epi2me-labs/wf-metagenomics --fastq ./basecalling/pass/ --out_dir nextflow-output/minimap/ --minimap2 --report_name minimap --threads 20

I used some other variations of the command too, but all of them returned this error message

Kind regards,
Hans-Peter

**Comment by Karhide** [comment]
Hi there,

Apologies for this error, I believe a subsequent update has fixed it. Could you confirm that it is fixed now?

Thanks

**Comment by nggvs** [comment]
Hi,
Thank you for using the workflow. Could you confirm if this issue has been solved? I'll close this ticket on the assumption things are now resolved. Please feel free to open it again if you are still having problems.
