### ISSUE TITLE
[Bug]: kraken_pipeline:kraken_server terminated 

### ISSUE THREAD

**Issue by clalgudi** [epi2me-labs/wf-metagenomics#51]
### What happened?

Everytime I run wf_metagenomics through EPI2ME Labs application, it always outputs that "Process `kraken_pipeline:kraken_server` terminated with an error exit status (71) -- Error is ignored". The actual run never finishes.

I am using Kraken2 with the PlusPFP-8 database on a single .fastq file containing multiple sequences. The rest of the settings are default. 

Any help/tips as to why this is happening is much appreciated!

### Operating System

macOS

### Workflow Execution

EPI2ME Labs desktop application

### Workflow Execution - CLI Execution Profile

None

### Workflow Version

wf-metagenomics v2.2.1

### Relevant log output

```shell
Checking inputs.
Checking fastq input.
[98/fd892e] Submitted process > fastcat (1)
[fa/251be0] Submitted process > kraken_pipeline:getVersions
[c6/a69df6] Submitted process > kraken_pipeline:getParams
[11/019f91] Submitted process > kraken_pipeline:output (1)
[8b/e808e0] Submitted process > kraken_pipeline:kraken2_client (1)
Staging foreign file: https://genome-idx.s3.amazonaws.com/kraken/k2_pluspfp_08gb_20230314.tar.gz
Staging foreign file: https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump_archive/new_taxdump_2023-03-01.zip
[6f/4335d4] Submitted process > kraken_pipeline:output (2)
[f2/685c69] Submitted process > kraken_pipeline:unpackTaxonomy
[1b/fe2ace] Submitted process > kraken_pipeline:unpackDatabase
[a5/65d6ac] Submitted process > kraken_pipeline:determine_bracken_length
[4f/37bf99] Submitted process > kraken_pipeline:kraken_server
[4f/37bf99] NOTE: Process `kraken_pipeline:kraken_server` terminated with an error exit status (71) -- Error is ignored
```

**Comment by nggvs** [comment]
Hi,

Thank you for using the workflow! Could I ask you which is the RAM that is available?  Memory available to the workflow should be slightly higher than size of the database (8GB).

**Comment by clalgudi** [comment]
Hello! Is this a setting/parameter than I can change when I run the workflow? I have also tried running this on terminal using command line wf-metagenomics, but get the same error that kraken_server failed and terminated.

Thanks!

**Comment by nggvs** [comment]
Hi,

The wf should run in the EPI2ME Labs application and in the command line. Could you send me the command you are using and which is the RAM that is available? Is it possible to change the memory with a parameter. You can modify it in the EPI2MELabs in the Nextflow configuration menu (is one of the options that appears when you are setting up a run) and local memory.
