### ISSUE TITLE
[Question]: Confidence Parameters for Kraken2 and Bracken

### ISSUE THREAD

**Issue by clalgudi** [epi2me-labs/wf-metagenomics#54]
### What happened?

I ran the workflow and successfully got the wf-metagenomics report, but was am still in the dark about what parameters are being run internally for kraken2 and bracken? Can I modify these - for example, the confidence interval? And is the only output the wf-metagenomics html report file, or is there detailed data for each read and its corresponding taxonomy and confidence level for that read?

### Operating System

Windows 10

### Workflow Execution

EPI2ME Labs desktop application

### Workflow Execution - CLI Execution Profile

None

### Workflow Version

wf-metagenomics v2.2.1

### Relevant log output

```shell
No relevant log output
```

**Comment by nggvs** [comment]
Hi,
Apologies for the late answer.  The parameters that are used in kraken2 are by default. The length used for bracken depends on the database. For the default database (ncbi_16s_18s) is 1000, but it can be customized providing a different kmer_distrib file with the flag `--bracken_dist` or directly with the flag `--bracken_length`. 

At this moment, we don't provide the input for each read, but in the meantime you could maybe use [kraken tools - extract kraken reads](https://github.com/jenniferlu717/KrakenTools#extract_kraken_readspy)

**Comment by Ge0rges** [comment]
@nggvs is it possible to modify the kraken2 confidence threshold? It defaults to 0.

**Comment by nggvs** [comment]
Hi, thank you for using the workflow!
I will take a look to see if it is possible to include it as an option.

**Comment by Ge0rges** [comment]
Great! It's a pretty important parameter, see this [paper](https://www.microbiologyresearch.org/content/journal/mgen/10.1099/mgen.0.000949) on the subject.

**Comment by nggvs** [comment]
Hi, 
The kraken2 confidence threshold has been added for the next release under the flag `--kraken2_confidence`. I'll let you know once it is released

**Comment by nggvs** [comment]
Hi @Ge0rges !
Version 2.5.0 has been released yesterday. You can use the option `--kraken2_confidence` . Please, let us know anything else, otherwise consider to close the issue.

**Comment by nggvs** [comment]
Hi @clalgudi !

We have added the kraken2 files which contains the assignment per read. To use this option, you should use the flag: `--include_kraken2_assignments` and these files will be placed in a folder called `kraken_reads_assignments` within the output folder.

**Comment by Ge0rges** [comment]
Great thank you! I consider this issue closed on my end.
