### ISSUE TITLE
Big ref2taxid.targloci.tsv

### ISSUE THREAD

**Issue by f3dja** [epi2me-labs/wf-metagenomics#56]
### Ask away!

If ref2taxid.targloci.tsv gets big taxid (format_minimap2.py) will become float64 instead of int64 since the dtype is not specified: 

`ref2taxid_df = pd.read_csv(reference2taxid, sep='\t', names=['acc', 'taxid'], index_col=0)`

Hence you might want to add `dtype = {'taxid': int}` to avoid a bug.

EDIT: specifying the type did not work as smooth as intended; however, leaving the type unspecified and modifying the line 

`taxid = ref2taxid_df.at[aln.reference_name, 'taxid']`

to

`taxid = ref2taxid_df.at[aln.reference_name, 'taxid'].astype('int64')` worked well.

Now I can use to wf-metagenomics with minimap2 and the full nt.gz...

**Comment by nggvs** [comment]
Hi,
Thank you for using the wf and for your suggestion, I will update this in the next release!

**Comment by nggvs** [comment]
I have included this in the latest version (v2.4.4).
Again, thank you very much for your suggestion and please don't hesitate to comment any other thing!
If you consider this has been already solved, could you close the issue?
