### ISSUE TITLE
Input path test_data does not exist.

### ISSUE THREAD

**Issue by mjbroerman** [epi2me-labs/wf-metagenomics#57]
### Operating System

macOS

### Workflow Version

v2.4.2

### Workflow Execution

Command line

### CLI command run

`nextflow run epi2me-labs/wf-metagenomics --fastq test_data`

### Workflow Execution - CLI Execution Profile

standard (default)

### What happened?

file not found, but this works:
`nextflow run epi2me-labs/wf-metagenomics --fastq /Users/matt/.nextflow/assets/epi2me-labs/wf-metagenomics/test_data/case03_baf`

### Relevant log output

```shell
Checking inputs.
Checking fastq input.
Input path test_data does not exist.
```

**Comment by SamStudio8** [comment]
Hi @mjbroerman, the README is written implying you are running the commands in the repository which is misleading, thank you for reporting this. It looks like you have been able to find the test data OK in your `assets` directory. You may be interested in exploring our workflows through the EPI2ME Desktop application which can automatically download and run our workflows on demo data for you. It can be downloaded from here https://labs.epi2me.io/downloads/.
