### ISSUE TITLE
Sample sheet not recognized by workflow

### ISSUE THREAD

**Issue by shelbyreimer** [epi2me-labs/wf-metagenomics#6]
I have been able to run the workflow with a single sample and have the workflow rename the output file with the sample ID, and I have also been able to run it with barcoded multiple samples with the output files labeled with barcode # (i.e. barcode01.braken_report.txt) with no issues. However, when I try to specify a sample sheet with sample ID and barcode #, the workflow fails to run and I get the below error:

_Error executing process > 'checkSampleSheet'
Caused by:
  Process `checkSampleSheet` terminated with an error exit status (1)
Command executed:
  check_sample_sheet.py sample_sheet.txt samples.txt
Command exit status:
  1
Command output:
  (empty)
Command error:
  WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
  /home/epi2melabs/conda/lib/python3.8/site-packages/pandas/util/_decorators.py:311: ParserWarning: Falling back to the 'python' engine because the 'c' eng
ine does not support sep=None with delim_whitespace=False; you can avoid this warning by specifying engine='python'.
    return func(*args, **kwargs)
  Traceback (most recent call last):
    File "/Users/JohnSmith/.nextflow/assets/epi2me-labs/wf-metagenomics/bin/check_sample_sheet.py", line 26, in main
      raise IOError()
  OSError
  During handling of the above exception, another exception occurred:
  Traceback (most recent call last):
    File "/Users/JohnSmith/.nextflow/assets/epi2me-labs/wf-metagenomics/bin/check_sample_sheet.py", line 41, in <module>
      main()
    File "/Users/JohnSmith/.nextflow/assets/epi2me-labs/wf-metagenomics/bin/check_sample_sheet.py", line 28, in main
      raise IOError(
  OSError: Could not parse sample sheet, it must contain two columns named 'barcode' and 'sample_id' or 'alias'.
Work dir:
  /Users/JohnSmith/Desktop/EPI2ME_wf-metagenomics/work/c3/f25acbd408f0e16f71c1be7dd2ca1f
Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line_

It seems the description of the sample sheet CSV file is wrong. It says to contain three columns: CSV file with columns named barcode, sample_name and type. Permissible if passing a directory containing barcodeXX sub-directories.
but this gives an error: OSError: Could not parse sample sheet, it must contain two columns named 'barcode' and 'sample_id' or 'alias'.

How can I fix the format of this sample sheet so that the workflow recognizes the sample IDs and labels the output files properly?

**Comment by nggvs** [comment]
Hi,

Thank you for using the workflow. Apologies for the late answer.

The sample sheet is a CSV file with columns named `barcode` and `alias`. Extra columns are allowed. A `type` column is required for certain workflows and should have the following values; `test_sample`, `positive_control`, `negative_control`, `no_template_control`.

We'll change this in the documentation. In the meanwhile, could you run the latest version and confirm if you are still having the same problem or we'll close this ticket on the assumption things are now resolved.
