### ISSUE TITLE
Support directory of sample FASTQs

### ISSUE THREAD

**Issue by Ge0rges** [epi2me-labs/wf-metagenomics#60]
### Is your feature related to a problem?

Often it is nice to work with merged FASTQ files, e.g. one FASTQ file per barcode. However this workflow interprets that as a directory of samples.

### Describe the solution you'd like

A flag such that the workflow interprets each FASTQ in a directory as being different samples.

### Describe alternatives you've considered

Having an unnecessarily layered file structure. Optionally, a list of FASTQ files can be passed and each is interpreted as being its own sample.

**Comment by nggvs** [comment]
Hi,
Thank you for using the workflow and for your suggestion!
Right now we don't support that option, although we can consider it. Meanwhile, you can place each individual FASTQ file into its own directory, so that they can be treated independently.

**Comment by nggvs** [comment]
Hi @Ge0rges ,
I will close this issue for now as it is not intended to be implemented in the near future. Nevertheless, we keep it in mind!
Thank you for your feedback and please feel free on making more suggestions!
