### ISSUE TITLE
Viruses with minimap pipeline

### ISSUE THREAD

**Issue by sarah-buddle** [epi2me-labs/wf-metagenomics#61]
### Ask away!

I am trying to run the minimap version of the pipeline with a custom database, based on sequences downloaded from Refseq and indexed using minimap. The command I have used is:
`nextflow run epi2me-labs/wf-metagenomics -profile singularity -with-tower -w ${results}/work \
--fastq ${data}/${run}/${sample}_${run}.fq.gz 
--classifier minimap2
--database $minimap_db_epi2me
--taxonomy $taxdump 
--ref2taxid $epi2me_accession2taxid 
--out_dir ${results}/epi2me_minimap/${run}/${sample}`
The pipeline runs without errors and completes. I get the following output, with the majority of reads classified as unknown:
![image](https://github.com/epi2me-labs/wf-metagenomics/assets/69523252/bec2aec8-208a-406f-aa9a-0d53d0539358)
However, I am expecting some viruses in this sample, and I find them using the Kraken2/Bracken version of the pipeline (using a database built with the same fasta file as my minimap custom database). Is there a reason why I might not find viruses with this pipeline despite using them in the database?
I am using names.dmp and nodes.dmp from RefSeq as taxonomy and my ref2taxid is adapted from nucl_db.accession2taxid, with excerpt shown below.
![image](https://github.com/epi2me-labs/wf-metagenomics/assets/69523252/ebfc7510-c3a0-4529-bf1d-7e73925bb3cc)

**Comment by nggvs** [comment]
Hi,
Thank you for using the workflow! In the minimap2 pipeline you need to use the flag `--reference` to provide the FASTA/MMI file used as reference. The flag `--database` is just for kraken2 pipeline.

You can check [this](https://labs.epi2me.io/metagenomic-databases/) for more info.

Please try with that flag and let me know if it is working!

**Comment by sarah-buddle** [comment]
OK thank you! I will try with that and let you know.

**Comment by nggvs** [comment]
Hi @sarah-buddle !

Is there any updates on this? Were you able to run the workflow with minimap2 using your custom database?

**Comment by nggvs** [comment]
Hi @sarah-buddle,

Has your issue already been solved? Please consider closing the issue in that case or we'll close it assuming that it has been already solved.

Thank you very much!
