### ISSUE TITLE
amplicon-seq analysis with ncbi_16s_18s_28s_ITS

### ISSUE THREAD

**Issue by HannahBenisty** [epi2me-labs/wf-metagenomics#65]
### Ask away!

Hi! I have a question regarding the protocol I am currently planning. My objective is to identify eukaryotes within my samples, and I intend to prepare amplicons that cover almost the entire eukaryotic rRNA operon (18s, 28s, ITS). I was wondering if it would be appropriate to use the "ncbi_16s_18s_28s_ITS" database for wf-metagenomics for the analysis of these long amplicon sequences. 
Thanks!

**Comment by nggvs** [comment]
Hi @HannahBenisty,
The ncbi_16s_18s_28s_ITS contains sequences from the 16SrRNA gen, 18SrRNA gen, 28S rRNA and ITS but not the whole operon. You can use this database or make a custom database with sequences for the whole operon  and provide it to the workflow.
