### ISSUE TITLE
html report

### ISSUE THREAD

**Issue by HannahBenisty** [epi2me-labs/wf-metagenomics#67]
### Ask away!

Hi!

Do you have documentation about the html report? Could you please indicate me to which cutoff corresponds in the section of lineages?

Thanks 
![image](https://github.com/epi2me-labs/wf-metagenomics/assets/94696499/d2e8fbd9-ea14-4ef0-8e7d-4d644b2c546b)

**Comment by nggvs** [comment]
Hi @HannahBenisty ,

That's an abundance cut-off. Only those lineages with an abundance higher than that cut-off from the total are shown in the sankey plot. Thanks for noticing it, I will add it in the docs.

**Comment by HannahBenisty** [comment]
Thanks!

Is there a way to select a cutoff of how well should the read match the reference gene in the database to be considered?

**Comment by nggvs** [comment]
No, there isn't.  Why would you think it could be useful?

In the kraken2 pipeline you can have a ['confidence score'](https://github.com/DerrickWood/kraken2/wiki/Manual#confidence-scoring) of the taxonomic assignment using the `--kraken2_confidence` parameter.

In the minimap2 pipeline, there isn't something analogous, but in the next release you would be able to use the `--minimap2_by_reference` to get the sequencing depth of each reference and the coverage, which could be useful.

**Comment by nggvs** [comment]
Hi @HannahBenisty ,
Is your question solved? If it is that case, would you mind to close the issue? Otherwise we will close it assuming it has been already answered.
Thank you very much!
