### ISSUE TITLE
How to export diversity table? 

### ISSUE THREAD

**Issue by msubirana** [epi2me-labs/wf-metagenomics#69]
### Ask away!

How can I export the Diversity table per each sample with Shannon Diversity Index, Simpson's Diversity Index...?

**Comment by mattdmem** [comment]
Hello - thanks for your interest in our workflows - these is an export button below the table in the report - simply click and a csv of the table will download.

<img width="1430" alt="Screenshot 2023-10-12 at 21 29 53" src="https://github.com/epi2me-labs/wf-metagenomics/assets/16154750/b71535ef-79bc-47e6-aaac-baa86d0bdecb">

Matt

**Comment by msubirana** [comment]
I mean without enter to the html, like "abundance_table_species.tsv" if it is not possible to export, how can I calculate them from "abundance_table_species.tsv" table.
