### ISSUE TITLE
And i am not able to find any proper manual or tutorial for EPI2ME command line version using nextflow with docker?

### ISSUE THREAD

**Issue by ap1438** [epi2me-labs/wf-metagenomics#7]
nextflow run epi2me-labs/wf-metagenomics --fastq reads.fastq.gz -profile standard --out_dir test1

I am using this command with the test data available but there is nothing in the output?
And i am not able to find any proper manual or tutorial for EPI2ME command line version using nextflow with docker?

**Comment by mattdmem** [comment]
Hi @ap1438 

Running `nextflow run epi2me-labs/wf-metagenomics --help` prints out the usage instructions but I agree that this is not clear. You need to additionally specify a method of read classification; you can add `--kraken2` or `--minimap2` (or both) to your command and it should work. We'll make this clearer in an upcoming release. Let me know how you get on.

Thanks

Matt

**Comment by ap1438** [comment]
$ nextflow run epi2me-labs/wf-metagenomics --fastq --kraken2 reads.fastq -profile standard
N E X T F L O W  ~  version 22.04.0
Launching `https://github.com/epi2me-labs/wf-metagenomics` [admiring_nightingale] DSL2 - revision: b0d52f1048 [master]

ERROR: Validation of pipeline parameters failed!


* --fastq: expected type: String, found: Boolean (true)


* --kraken2: expected type: Boolean, found: String (reads.fastq)

This is the error that i am getting. I am not able to understand whats going wrong here.

**Comment by mattdmem** [comment]
There is an error in your command , this should work:

```nextflow run epi2me-labs/wf-metagenomics --fastq reads.fastq --kraken2 -profile standard```

**Comment by ap1438** [comment]
nextflow run epi2me-labs/wf-metagenomics --fastq reads.fastq.gz --kraken2 -profile standard
N E X T F L O W  ~  version 22.04.0
Launching `https://github.com/epi2me-labs/wf-metagenomics` [nasty_mccarthy] DSL2 - revision: b0d52f1048 [master]
Core Nextflow options
  revision       : master
  runName        : nasty_mccarthy
  containerEngine: docker
  launchDir      : /mnt/USB2/Tools/EPI2ME/Test_10_05_22
  workDir        : /mnt/USB2/Tools/EPI2ME/Test_10_05_22/work
  projectDir     : /home/.nextflow/assets/epi2me-labs/wf-metagenomics
  userName       : group
  profile        : standard
  configFiles    : /home/.nextflow/assets/epi2me-labs/wf-metagenomics/nextflow.config

Core options
  fastq          : reads.fastq.gz
  sources        : [TARGLOCI:[reference:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-ribosomal-survey/targeted_loci/ncbi_targeted_loci_16s_18s.fna, refindex:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-ribosomal-survey/targeted_loci/ncbi_targeted_loci_16s_18s.fna.fai, database:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-ribosomal-survey/targeted_loci/ncbi_targeted_loci_kraken2.tar.gz, kmer_dist:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-ribosomal-survey/targeted_loci/database1000mers.kmer_distrib, ref2taxid:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-ribosomal-survey/targeted_loci/ref2taxid.targloci.tsv, taxonomy:https://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz]]

Kraken2 options
  kraken2        : true

!! Only displaying parameters that differ from the pipeline defaults !!
------------------------------------------------------
If you use wf-metagenomics for your analysis please cite:

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x



Checking inputs.
Checking fastq input.
Single file input detected.
executor >  local (7)
executor >  local (7)
[f3/1e9c53] process > handleSingleFile (1)            [100%] 1 of 1 ✔
[16/354f8c] process > pipeline:unpackTaxonomy         [100%] 1 of 1 ✔
[01/6dad77] process > pipeline:unpackDatabase         [100%] 1 of 1 ✔
[d0/11026c] process > pipeline:combineFilterFastq (1) [100%] 1 of 1 ✔
[32/3e509d] process > pipeline:kraken2 (1)            [100%] 1 of 1, failed: 1 ✘
[-        ] process > pipeline:bracken                -
[37/4d712f] process > pipeline:getVersions            [100%] 1 of 1 ✔
[80/563f93] process > pipeline:getParams              [100%] 1 of 1 ✔
[-        ] process > pipeline:makeReport             -
[-        ] process > output                          -
WARN: Input tuple does not match input set cardinality declared by process `pipeline:makeReport` -- offending value: [[]]
Error executing process > 'pipeline:kraken2 (1)'

Caused by:
  Missing output file(s) `*.classified.fastq` expected by process `pipeline:kraken2 (1)`

Command executed:

  kraken2         --db database_dir         --threads 8         --report reads.kraken2_report.txt         --classified-out reads.kraken2.classified.fastq         --unclassified-out reads.kraken2.unclassified.fastq         reads.fastq > reads.kraken2.assignments.tsv
  awk -F '\t' '{print $3}' reads.kraken2.assignments.tsv > taxids.tmp
  taxonkit         --data-dir taxonomy_dir         lineage -R taxids.tmp         | aggregate_lineages.py -p reads.kraken2

Command exit status:
  0

Command output:
  (empty)

Command error:
  Loading database information... done.
  0 sequences (0.00 Mbp) processed in 0.003s (0.0 Kseq/m, 0.00 Mbp/m).
    0 sequences classified (-nan%)
    0 sequences unclassified (-nan%)

Work dir:
  /mnt/USB2/Tools/EPI2ME/Test_10_05_22/work/32/3e509d2e73f6884557a1a3368c8568

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

This is the error i am getting in Kraken2 module.

**Comment by ap1438** [comment]
nextflow run epi2me-labs/wf-metagenomics --fastq reads.fastq.gz --minimap2 -profile standard
N E X T F L O W  ~  version 22.04.0
Launching `https://github.com/epi2me-labs/wf-metagenomics` [kickass_kirch] DSL2 - revision: b0d52f1048 [master]
Core Nextflow options
  revision       : master
  runName        : kickass_kirch
  containerEngine: docker
  launchDir      : /mnt/USB2/Tools/EPI2ME/Test_10_05_22
  workDir        : /mnt/USB2/Tools/EPI2ME/Test_10_05_22/work
  projectDir     : /home/.nextflow/assets/epi2me-labs/wf-metagenomics
  userName       : group
  profile        : standard
  configFiles    : /home/.nextflow/assets/epi2me-labs/wf-metagenomics/nextflow.config

Core options
  fastq          : reads.fastq.gz
  sources        : [TARGLOCI:[reference:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-ribosomal-survey/targeted_loci/ncbi_targeted_loci_16s_18s.fna, refindex:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-ribosomal-survey/targeted_loci/ncbi_targeted_loci_16s_18s.fna.fai, database:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-ribosomal-survey/targeted_loci/ncbi_targeted_loci_kraken2.tar.gz, kmer_dist:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-ribosomal-survey/targeted_loci/database1000mers.kmer_distrib, ref2taxid:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-ribosomal-survey/targeted_loci/ref2taxid.targloci.tsv, taxonomy:https://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz]]

Minimap2 options
  minimap2       : true

!! Only displaying parameters that differ from the pipeline defaults !!
------------------------------------------------------
If you use wf-metagenomics for your analysis please cite:

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x



Checking inputs.
Checking fastq input.
Single file input detected.
executor >  local (7)
[c5/3a08ea] process > handleSingleFile (1)            [100%] 1 of 1 ✔
executor >  local (7)
[c5/3a08ea] process > handleSingleFile (1)            [100%] 1 of 1 ✔
[66/e0822d] process > pipeline:unpackTaxonomy         [100%] 1 of 1 ✔
[2f/f9c0e2] process > pipeline:combineFilterFastq (1) [100%] 1 of 1 ✔
[f8/3f5b10] process > pipeline:minimap2 (1)           [100%] 1 of 1 ✔
[64/baab1c] process > pipeline:getVersions            [100%] 1 of 1 ✔
[16/f56d8a] process > pipeline:getParams              [100%] 1 of 1 ✔
[a0/d87c5e] process > pipeline:makeReport             [100%] 1 of 1, failed: 1 ✘
[-        ] process > output                          [  0%] 0 of 5
Error executing process > 'pipeline:makeReport'

Caused by:
  Process `pipeline:makeReport` terminated with an error exit status (1)

Command executed:

  report.py         wf-metagenomics-report.html         --versions versions         --params params.json         --summaries reads.stats         --lineages reads.minimap2.lineages.json         --vistempl report-visualisation.html

Command exit status:
  1

Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File "/home/.nextflow/assets/epi2me-labs/wf-metagenomics/bin/report.py", line 117, in <module>
      main()
    File "/home/.nextflow/assets/epi2me-labs/wf-metagenomics/bin/report.py", line 100, in main
      section=fastcat.full_report(
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/aplanat/components/fastcat.py", line 140, in full_report
      read_length = read_length_plot(stats, min_len=min_len, max_len=max_len)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/aplanat/components/fastcat.py", line 29, in read_length_plot
      mean_length = total_bases / len(seq_summary)
  ZeroDivisionError: division by zero

Work dir:
  /mnt/USB2/Tools/EPI2ME/Test_10_05_22/work/a0/d87c5e901b0391e95e95b69006cea1

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

And This from minimap2 module.

**Comment by ap1438** [comment]
Hi,
I just wanted to put a reminder. Is this problem solved.Because i wanted to use the software for my analysis.

**Comment by mattdmem** [comment]
Hello - could you possibly provide your data? My feeling is that you have no results? Alternatively can you run the fastq data in this repository. This will help us determine if it is the data you have or an issue with the workflow. The workflow is tested regularly with the test data so that should work.

https://github.com/epi2me-labs/wf-metagenomics/tree/master/test_data

Thanks!

**Comment by ap1438** [comment]
Thank you for your response 
So about the data that i am using is the same provided in  the repository.
Initially i downloaded with

 wget -c https://github.com/epi2me-labs/wf-metagenomics

Then when it didn't work i downloaded it from repository directly using   

wget -c https://github.com/epi2me-labs/wf-metagenomics/blob/master/test_data/reads.fastq.gz.

So, I think the error is with the workflow  not with the data because the data used are test data provided in the repository only.

For Kraken2 as seen the error is with the makeReport pipeline

And for minimap2  its the same makeReport pipeline issue.

**Comment by mattdmem** [comment]
I think your download command has the wrong addess... if I do `wget -c https://github.com/epi2me-labs/wf-metagenomics/blob/master/test_data/reads.fastq.gz.` then my file is html which would explain why the workflow isn't working in your hands - are their reads in the fastq file you downloaded?

`wget https://github.com/epi2me-labs/wf-metagenomics/raw/master/test_data/reads.fastq.gz` is the correct download command.

Thanks

**Comment by ap1438** [comment]
Thanks for your quick response .So, firstly the files  from link 2 were corrupted as identified by you.And you were right there were no reads in it. But the files from the first link i.e. 
wget -c https://github.com/epi2me-labs/wf-metagenomics 

were correct with same sequence provided in the link by you i.e.
wget https://github.com/epi2me-labs/wf-metagenomics/raw/master/test_data/reads.fastq.gz

I also tried with the read file downloaded provided by you mentioned above. But the problem remains the same i.e. with the make report pipeline.

As far as i understand the error is with the pipeline.

**Missing output file(s) *.classified.fastq expected by process pipeline:kraken2 (1)-kraken2

**Process pipeline:makeReport terminated with an error exit status (1)-minimap2

I even used the updated workflow released yesterday but the error remains the same.

Please help me out resolving this issue .

Thanks

**Comment by mattdmem** [comment]
Morning!

I just checked and the following works for me, can you please try?

```nextflow run epi2me-labs/wf-metagenomics --fastq reads.fastq.gz --kraken2 ```


```
$ nextflow run epi2me-labs/wf-metagenomics --fastq reads.fastq.gz.1 --kraken2 

N E X T F L O W  ~  version 21.10.6
Pulling epi2me-labs/wf-metagenomics ...
 downloaded from https://github.com/epi2me-labs/wf-metagenomics.git
Launching `epi2me-labs/wf-metagenomics` [agitated_goldberg] - revision: a0bd9ca590 [master]
Core Nextflow options
  revision       : master
  runName        : agitated_goldberg
  containerEngine: docker
  launchDir      : /Users/xxx/work/wf-metagenomics
  workDir        : /Users/xxx/work/wf-metagenomics/work
  projectDir     : /Users/xxx/.nextflow/assets/epi2me-labs/wf-metagenomics
  userName       : xxx
  profile        : standard
  configFiles    : /Users/xxx/.nextflow/assets/epi2me-labs/wf-metagenomics/nextflow.config

Core options
  fastq          : reads.fastq.gz
  sources        : [....]

!! Only displaying parameters that differ from the pipeline defaults !!
------------------------------------------------------
If you use wf-metagenomics for your analysis please cite:

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x



Checking inputs.
Checking fastq input.
Single file input detected.
executor >  local (18)
[68/3fd1b7] process > handleSingleFile (1)            [100%] 1 of 1 ✔
[56/5eff92] process > pipeline:unpackTaxonomy         [100%] 1 of 1 ✔
[4f/f4d5dd] process > pipeline:unpackDatabase         [100%] 1 of 1 ✔
[06/a570f5] process > pipeline:combineFilterFastq (1) [100%] 1 of 1 ✔
[23/383974] process > pipeline:kraken2 (1)            [100%] 1 of 1 ✔
[ff/5b913c] process > pipeline:bracken (1)            [100%] 1 of 1 ✔
[6a/ec04b3] process > pipeline:getVersions            [100%] 1 of 1 ✔
[6b/514ceb] process > pipeline:getParams              [100%] 1 of 1 ✔
[16/519e0e] process > pipeline:makeReport             [100%] 1 of 1 ✔
[bf/7e2eed] process > output (7)                      [100%] 9 of 9 ✔
Completed at: 17-May-2022 09:31:22
Duration    : 3m 22s
CPU hours   : (a few seconds)
Succeeded   : 18


```


If you can't use the `docker` profile you could try `conda`?

Thanks

**Comment by ap1438** [comment]
Thanks for your insight and quick response. You were right the issue was with something else not with the script. Its still not running in the server but i have tried it in local it works fine. 

So for time being i will use local for analysis. But in the mean time will also  try to find out why it is not running on server And if found, will update here in the issue section.

**Comment by Midnighter** [comment]
I get the exact same errors with neither kraken2 nor minimap2 producing an output. I downloaded the test data and confirmed that it contains 1000 reads. Then run the pipeline as follows:

```bash
#!/usr/bin/env bash

set -euo pipefail

export NXF_VER='21.10.6'

pipeline='https://github.com/epi2me-labs/wf-metagenomics'

nextflow pull $pipeline

nextflow -c 'local.config' run \
    $pipeline \
    -r 'master' \
    -params-file 'params.yml' \
    -resume
```

`params.yml`
```yml
fastq: "/.../data/reads.fastq.gz"
minimap2: true
kraken2: true
threads: 30
```

I also tried to run it with revision v1.1.4 and nextflow 22.04.3 same error. Runs with docker and standard profile.
