### ISSUE TITLE
How to export diversity table not from the html?

### ISSUE THREAD

**Issue by msubirana** [epi2me-labs/wf-metagenomics#70]
### Ask away!

Is it possible to export diversity table not from the html but as a file, similarly like 'abundance_table_species.tsv'. If is it not possible, could it be possible to calculate the diversity index from abundance_table_species.tsv table?

**Comment by nggvs** [comment]
Hi @msubirana ,

Thank you for using the pipeline! Unfortunately it is still not possible to have the diversity table in the output folder. I take a note to do it in a future release. Meanwhile you can use the abundance_table_species.tsv to calculate the diversity indexes.

**Comment by msubirana** [comment]
Hi and thanks for the quick answer.

Any hint about how to calculate from abundance_table_species.tsv?

**Comment by nggvs** [comment]
Apologies for the late answer, there are different options: you can use [vegan](https://github.com/vegandevs/vegan) or [phyloseq](https://www.bioconductor.org/packages/release/bioc/html/phyloseq.html) packages in R, or use the diversity tools within the [KrakenTools package](https://github.com/jenniferlu717/KrakenTools).

**Comment by msubirana** [comment]
thanks!
