### ISSUE TITLE
pipeline hangs on client/server

### ISSUE THREAD

**Issue by jagos01** [epi2me-labs/wf-metagenomics#71]
### Operating System

Other Linux (please specify below)

### Other Linux

Ubuntu 20.04

### Workflow Version

v2.6.1

### Workflow Execution

Command line

### CLI command run

nextflow run epi2me-labs/wf-metagenomics --fastq /home/sco/Data_DB/Analyis/reads --out_dir /home/sco/Data_DB/Analyis/wf_metagenomics/k2_std_2.6.1/C0.dorado.v0.4.1bacmeth.duplex.only.q8.nf.q16.l1200.fastq --database /home/sco/Downloads/k2_pluspf_08gb_20230605/  --taxonomy /home/sco/Downloads/taxdmp_2023-06-01/  --bracken_dist /home/sco/Downloads/k2std_distance/database1000mers.kmer_distrib --threads 4

### Workflow Execution - CLI Execution Profile

standard (default)

### What happened?

Pipeline hangs on kraken2_server with this dataset (1.8GB).  These reads were basecalled with Dorado (v0.4.1) using a model from the Nanopore/rerio repository.  When I use a different dataset (much smaller) basecalled with guppy or Dorado (v0.2.1) everything works fine.  I have let this run overnight without any further progress in classification.  Is there a limit to the file size for classification?  Two logs for the kraken server and client are provided below.

.command.err (for server)
Loading database information...
Successfully loaded index.
Starting stream handler.
12000 sequences (112.88 Mbp) processed in 5.04s (142.75 Kseq/m, 1342.83 Mbp/m).
	11997 sequences classified (99.97%)
	3 sequences unclassified (0.03%)

Finished stream handler.

.command.log (server)
Creating classification thread pool with 2 thread(s).
Loading database information...
Successfully loaded index.
Server listening on localhost:8080. Press Ctrl-C to end.
Starting stream handler.
12000 sequences (112.88 Mbp) processed in 5.04s (142.75 Kseq/m, 1342.83 Mbp/m).
	11997 sequences classified (99.97%)
	3 sequences unclassified (0.03%)

Finished stream handler.

.command.err (client)
[21:26:44 - matplotlib.font_manager] generated new fontManager
[21:26:44 - workflow_glue] Starting entrypoint.
Connecting to server: localhost:8080.
Classifying sequence stream.
Server responded as ready.
Reading sequences from file: seqs.fastq.gz
Waiting before sending more. In-flight: 60000.

.command.log (client)
[21:26:44 - matplotlib.font_manager] generated new fontManager
[21:26:44 - workflow_glue] Starting entrypoint.
Connecting to server: localhost:8080.
Classifying sequence stream.
Server responded as ready.
Reading sequences from file: seqs.fastq.gz
Waiting before sending more. In-flight: 60000.

### Relevant log output

```shell
N E X T F L O W  ~  version 23.04.2
Launching `https://github.com/epi2me-labs/wf-metagenomics` [marvelous_blackwell] DSL2 - revision: 9d640fe641 [master]
WARN: NEXTFLOW RECURSION IS A PREVIEW FEATURE - SYNTAX AND FUNCTIONALITY CAN CHANGE IN FUTURE RELEASES

||||||||||   _____ ____ ___ ____  __  __ _____      _       _
||||||||||  | ____|  _ \_ _|___ \|  \/  | ____|    | | __ _| |__  ___
|||||       |  _| | |_) | |  __) | |\/| |  _| _____| |/ _` | '_ \/ __|
|||||       | |___|  __/| | / __/| |  | | |__|_____| | (_| | |_) \__ \
||||||||||  |_____|_|  |___|_____|_|  |_|_____|    |_|\__,_|_.__/|___/
||||||||||  wf-metagenomics v2.6.1-g9d640fe
--------------------------------------------------------------------------------
Core Nextflow options
  revision       : master
  runName        : marvelous_blackwell
  containerEngine: docker
  launchDir      : /home/sco
  workDir        : /home/sco/work
  projectDir     : /home/sco/.nextflow/assets/epi2me-labs/wf-metagenomics
  userName       : sco
  profile        : standard
  configFiles    : /home/sco/.nextflow/assets/epi2me-labs/wf-metagenomics/nextflow.config

Input Options
  fastq          : /home/sco/Data_DB/Analyis/reads

Reference Options
  database       : /home/sco/Downloads/k2_pluspf_08gb_20230605/
  taxonomy       : /home/sco/Downloads/taxdmp_2023-06-01/
  database_sets  : [ncbi_16s_18s:[reference:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s/ncbi_targeted_loci_16s_18s.fna, refindex:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s/ncbi_targeted_loci_16s_18s.fna.fai, database:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s/ncbi_targeted_loci_kraken2.tar.gz, kmer_dist:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s/database1000mers.kmer_distrib, ref2taxid:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s/ref2taxid.targloci.tsv, taxonomy:https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump_archive/taxdmp_2023-01-01.zip], ncbi_16s_18s_28s_ITS:[reference:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s_28s_ITS/ncbi_16s_18s_28s_ITS.fna, refindex:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s_28s_ITS/ncbi_16s_18s_28s_ITS.fna.fai, database:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s_28s_ITS/ncbi_16s_18s_28s_ITS_kraken2.tar.gz, kmer_dist:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s_28s_ITS/database1000mers.kmer_distrib, ref2taxid:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s_28s_ITS/ref2taxid.ncbi_16s_18s_28s_ITS.tsv, taxonomy:https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump_archive/taxdmp_2023-01-01.zip], SILVA_138_1:[database:null], PlusPF-8:[database:https://genome-idx.s3.amazonaws.com/kraken/k2_pluspf_08gb_20230314.tar.gz, taxonomy:https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump_archive/new_taxdump_2023-03-01.zip], PlusPFP-8:[database:https://genome-idx.s3.amazonaws.com/kraken/k2_pluspfp_08gb_20230314.tar.gz, taxonomy:https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump_archive/new_taxdump_2023-03-01.zip]]

Kraken2 Options
  bracken_dist   : /home/sco/Downloads/k2std_distance/database1000mers.kmer_distrib

Output Options
  out_dir        : /home/sco/Data_DB/Analyis/wf_metagenomics/k2_std_2.6.1/C0.dorado.v0.4.1bacmeth.duplex.only.q8.nf.q16.l1200.fastq

Advanced Options
  threads        : 4

!! Only displaying parameters that differ from the pipeline defaults !!
--------------------------------------------------------------------------------
If you use epi2me-labs/wf-metagenomics for your analysis please cite:

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x


--------------------------------------------------------------------------------
This is epi2me-labs/wf-metagenomics v2.6.1-g9d640fe.
--------------------------------------------------------------------------------
Checking inputs.
Note: Memory available to the workflow must be slightly higher than size of the database ncbi_16s_18s index (8GB) or consider to use --kraken2_memory_mapping
Note: Memory available to the workflow must be slightly higher than size of the database ncbi_16s_18s index (8GB) or consider to use the --kraken2_memory_mapping
Checking custom taxonomy mapping exists
Checking custom kraken2 database exists
Checking custom bracken2 database exists
Checking fastq input.
executor >  local (8)
[e0/a4d918] process > fastcat (1)                              [100%] 1 of 1 ✔
executor >  local (8)
[e0/a4d918] process > fastcat (1)                              [100%] 1 of 1 ✔
[skipped  ] process > kraken_pipeline:unpackTaxonomy           [100%] 1 of 1, stored: 1 ✔
[skipped  ] process > kraken_pipeline:unpackDatabase           [100%] 1 of 1, stored: 1 ✔
[6c/360b04] process > kraken_pipeline:determine_bracken_length [100%] 1 of 1 ✔
[-        ] process > kraken_pipeline:kraken_server            -
[0f/8799ea] process > kraken_pipeline:run_common:getVersions   [100%] 1 of 1 ✔
[41/3ea995] process > kraken_pipeline:run_common:getParams     [100%] 1 of 1 ✔
[-        ] process > kraken_pipeline:kraken2_client (1)       -
[-        ] process > kraken_pipeline:progressive_stats        -
[-        ] process > kraken_pipeline:progressive_kraken_re... -
[-        ] process > kraken_pipeline:progressive_bracken      -
[-        ] process > kraken_pipeline:createAbundanceTables    -
[-        ] process > kraken_pipeline:makeReport               -
[a7/3d059d] process > kraken_pipeline:output (2)               [100%] 2 of 2
[-        ] process > kraken_pipeline:stop_kraken_server       -
```

**Comment by nggvs** [comment]
Hi! Thank you for using the workflow!
Which are the resources of your device? I will try to reproduce your problem using the k2_pluspf_08gb_20230605 database and --threads 4

**Comment by nggvs** [comment]
Hi @jagos01 !
Unfortunately, I am not able to reproduce it, but as this is going to change in the next release, you might one to try the prerelease branch to see if the problem persists. Just to let you know, prerelease branch is not stable and may change, but you can give it a try. I will let you know once the stable one is released so that you can change to that one. Please let me know if you find something weird.
Thank you very much,

**Comment by jagos01** [comment]
Hello Natalie,
I just tried the prerelease branch with the same data and everything worked
fine.
Thanks

**Comment by nggvs** [comment]
Hi @jagos01  ,
new release (v2.7.0) is ready. It would be nice if you switch to this version as the pre-release is not stable. Also, if you consider the problem has already been solved, I would appreciate that you close the issue.

**Comment by jagos01** [comment]
Thanks.  I will update to v2.7.0 today.
