### ISSUE TITLE
html report - read summary

### ISSUE THREAD

**Issue by HannahBenisty** [epi2me-labs/wf-metagenomics#74]
### Ask away!

Hi! Usually a read summary appears in the read report, but now I have a run with 24 barcodes and the report starts at the lineages. It would be great if we could also see the read summary. Is there a way to find this information in other documents generated with this workflow. 
Many thanks!

**Comment by nggvs** [comment]
Hi!
Thanks for using the workflow. Which version are you using?

**Comment by HannahBenisty** [comment]
Hi, I am using minimap2 as classifier and added the option minimap2_by_reference. The version is the last one which I dowloaded using git clone gh repo clone epi2me-labs/wf-metagenomics.

**Comment by nggvs** [comment]
Ok, thank you very much! I will try to reproduce it. Could you run the workflow using demo or test_data to see if you also observe the same issue?

**Comment by HannahBenisty** [comment]
I have run a test data case 01 with the following options: --fastq test_data/case01/ --classifier minimap2 --minimap2_by_reference. Read summary not appearing.

**Comment by nggvs** [comment]
I'm trying to reproduce the error, but I see this using test_data or demo data with the latest version.
![image](https://github.com/epi2me-labs/wf-metagenomics/assets/122800769/2ba982e2-3ff2-4cd4-85aa-ff13fd5c53a6).

So, I'm not sure of what could be happening. Are you getting any error when you run the workflow? Could you paste the log?

**Comment by HannahBenisty** [comment]
Hi, 

here are the options I have used and the log: --fastq test_data/case01/ --classifier minimap2  --minimap2_by_reference

N E X T F L O W  ~  version 23.04.3
Launching `main.nf` [trusting_panini] DSL2 - revision: f09278680a
WARN: NEXTFLOW RECURSION IS A PREVIEW FEATURE - SYNTAX AND FUNCTIONALITY CAN CHANGE IN FUTURE RELEASES

WARN: Found unexpected parameters:
* --watch_path: false
* --bracken_dist: null
[2m- Ignore this warning: params.schema_ignore_params = "watch_path,bracken_dist" [0m


[0;92m||||||||||   [0m[2m_____ ____ ___ ____  __  __ _____      _       _
[0;92m||||||||||  [0m[2m| ____|  _ \_ _|___ \|  \/  | ____|    | | __ _| |__  ___
[0;33m|||||       [0m[2m|  _| | |_) | |  __) | |\/| |  _| _____| |/ _` | '_ \/ __|
[0;33m|||||       [0m[2m| |___|  __/| | / __/| |  | | |__|_____| | (_| | |_) \__ \
[0;94m||||||||||  [0m[2m|_____|_|  |___|_____|_|  |_|_____|    |_|\__,_|_.__/|___/
[0;94m||||||||||  [0m[1mwf-metagenomics v2.6.1[0m
[2m--------------------------------------------------------------------------------[0m
[1mCore Nextflow options[0m
  [0;34mrunName              : [0;32mtrusting_panini[0m
  [0;34mcontainerEngine      : [0;32msingularity[0m
  [0;34mlaunchDir            : [0;32m/nfs/users/rg/hbenisty/wf-meta/test_nat/wf-metagenomics[0m
  [0;34mworkDir              : [0;32m/nfs/users/rg/hbenisty/wf-meta/test_nat/wf-metagenomics/work[0m
  [0;34mprojectDir           : [0;32m/nfs/users/rg/hbenisty/wf-meta/test_nat/wf-metagenomics[0m
  [0;34muserName             : [0;32mhbenisty[0m
  [0;34mprofile              : [0;32mcrg[0m
  [0;34mconfigFiles          : [0;32m/nfs/users/rg/hbenisty/wf-meta/test_nat/wf-metagenomics/nextflow.config[0m

[1mInput Options[0m
  [0;34mfastq                : [0;32mtest_data/case01/[0m
  [0;34mclassifier           : [0;32mminimap2[0m

[1mReference Options[0m
  [0;34mdatabase_sets        : [0;32m[ncbi_16s_18s:[reference:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s/ncbi_targeted_loci_16s_18s.fna, refindex:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s/ncbi_targeted_loci_16s_18s.fna.fai, database:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s/ncbi_targeted_loci_kraken2.tar.gz, kmer_dist:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s/database1000mers.kmer_distrib, ref2taxid:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s/ref2taxid.targloci.tsv, taxonomy:https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump_archive/taxdmp_2023-01-01.zip], ncbi_16s_18s_28s_ITS:[reference:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s_28s_ITS/ncbi_16s_18s_28s_ITS.fna, refindex:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s_28s_ITS/ncbi_16s_18s_28s_ITS.fna.fai, database:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s_28s_ITS/ncbi_16s_18s_28s_ITS_kraken2.tar.gz, kmer_dist:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s_28s_ITS/database1000mers.kmer_distrib, ref2taxid:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s_28s_ITS/ref2taxid.ncbi_16s_18s_28s_ITS.tsv, taxonomy:https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump_archive/taxdmp_2023-01-01.zip], SILVA_138_1:[database:null], PlusPF-8:[database:https://genome-idx.s3.amazonaws.com/kraken/k2_pluspf_08gb_20230314.tar.gz, taxonomy:https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump_archive/new_taxdump_2023-03-01.zip], PlusPFP-8:[database:https://genome-idx.s3.amazonaws.com/kraken/k2_pluspfp_08gb_20230314.tar.gz, taxonomy:https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump_archive/new_taxdump_2023-03-01.zip]][0m

[1mMinimap2 Options[0m
  [0;34msplit_prefix         : [0;32mtrue[0m
  [0;34mminimap2_by_reference: [0;32mtrue[0m

!! Only displaying parameters that differ from the pipeline defaults !!
[2m--------------------------------------------------------------------------------[0m
If you use epi2me-labs/wf-metagenomics for your analysis please cite:

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x


[2m--------------------------------------------------------------------------------[0m
This is epi2me-labs/wf-metagenomics v2.6.1.
[2m--------------------------------------------------------------------------------[0m
Checking inputs.
WARN: Access to undefined parameter `real_time` -- Initialise it to a default value eg. `params.real_time = some_value`
Minimap2 pipeline.
Preparing databases.
Using default taxonomy database.
Using a default database.
Searching input for [.fastq, .fastq.gz, .fq, .fq.gz] files.
[skipping] Stored process > prepare_databases:download_reference_ref2taxid
[skipping] Stored process > prepare_databases:download_unpack_taxonomy
[6c/ecf4cd] Cached process > fastcat (3)
[6b/6e745d] Cached process > fastcat (2)
[91/a2d0d9] Cached process > fastcat (1)
[d4/ce9fbc] Cached process > minimap_pipeline:run_common:getVersions
[30/6c5f96] Cached process > minimap_pipeline:run_common:getParams
[c9/fce416] Cached process > minimap_pipeline:output (1)
[f5/bfa54f] Submitted process > minimap_pipeline:output (2)
[ff/a6b2d1] Submitted process > minimap_pipeline:minimap (1)
[b7/311ecf] Submitted process > minimap_pipeline:minimap (3)
[4b/6f488f] Submitted process > minimap_pipeline:minimap (2)
[f8/7b4c42] Submitted process > minimap_pipeline:getAlignmentStats (1)
[26/228e71] Submitted process > minimap_pipeline:getAlignmentStats (2)
[b0/ce42f0] Submitted process > minimap_pipeline:getAlignmentStats (3)
[5a/e02886] Submitted process > minimap_pipeline:createAbundanceTables
[41/d851ce] Submitted process > minimap_pipeline:output (3)
[a1/a95d25] Submitted process > minimap_pipeline:makeReport (1)
[34/1d4090] Submitted process > minimap_pipeline:output (4)

**Comment by nggvs** [comment]
Hi, 
Thank you for the log. From it I think you are using an old version of the workflow. Could you make sure you are using v2.7.0 and the master branch?

**Comment by HannahBenisty** [comment]
Ah ok, so I was using doing git clone from the link of the main page of the workflow. 

git clone https://github.com/epi2me-labs/wf-metagenomics.git

Which link should I use? Thanks!

**Comment by nggvs** [comment]
That is correct, would you mind to go into the folder wf-metagenomics that has been downloaded and run this?
`git status`

**Comment by HannahBenisty** [comment]
# On branch master
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#	modified:   nextflow.config
#	modified:   subworkflows/minimap_pipeline.nf
#
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#	._log
#	._nextflow.config
#	log
#	output/
#	store_dir/
#	subworkflows/._minimap_pipeline.nf
#	work/
no changes added to commit (use "git add" and/or "git commit -a")

**Comment by HannahBenisty** [comment]
Hi Natalia, 

I have tried again, and it works. Probably it was my fault because of messing with versions the nextflow config file.

**Comment by nggvs** [comment]
Hi @HannahBenisty ,

Glad to hear that!
I would suggest to:
```
git checkout -- nextflow.config
git checkout -- subworkflows/minimap_pipeline.nf
```
and then remove temporal files (subworkflows/._minimap_pipeline.nf, ._log, ._nextflow.config) to avoid any other issue.
Then you can run `git pull` to make sure everything is fine and you have the latest stable version.

Besides, if you don't mind to close the issue if it has been already solved, I would appreciate it!
