### ISSUE TITLE
taxonomy in the report

### ISSUE THREAD

**Issue by HannahBenisty** [epi2me-labs/wf-metagenomics#75]
### Ask away!

Hi! I have done some samples and everything looks good in the report except for the taxonomy. I put you an example of a sample that has around 50% of cyanobacteria (in the sunburst and lineages). However, this is not displayed in the taxonomy when comparing with the other samples. 

![Pasted Graphic 5](https://github.com/epi2me-labs/wf-metagenomics/assets/94696499/6fb29880-67a7-4896-b668-fb623a47bdbf)
![Pasted Graphic 7](https://github.com/epi2me-labs/wf-metagenomics/assets/94696499/1633ac88-e7a1-4c0e-9ef7-5e6f30a73f48)
![Pasted Graphic 6](https://github.com/epi2me-labs/wf-metagenomics/assets/94696499/58b24e96-a0a3-48f8-9990-3e93848aec63)

**Comment by nggvs** [comment]
Hi @HannahBenisty ,
Thank you for your feedback, always welcome! The barplot shows the most abundant taxa taking into account all the samples. Are cianos abundant just in one sample or in many of them? You can sort the abundance table by the total and the most abundant phyla are the ones that should appear in the barplot.

**Comment by HannahBenisty** [comment]
Ahhh ok! thanks a lot for the clarification! cianos are predominant in two samples.

**Comment by nggvs** [comment]
However, I've seen them in the barplot, which are the samples that contains more cyanos?

**Comment by HannahBenisty** [comment]
True! in the legend, that is why I got confused. samples are the ones starting with LK3 or LK5. In the images is the example if LK5

**Comment by nggvs** [comment]
Would you mind to send me the two abundance tables? you can export it from the report (at the phyla level) and then there is another one in the output.
