### ISSUE TITLE
non-assigned reads

### ISSUE THREAD

**Issue by HannahBenisty** [epi2me-labs/wf-metagenomics#76]
### Ask away!

Hi, I am looking at 16S rRNA gene sequencing data and I would like to know if there is a way to know the percentage of non-assigned reads per sample. Thanks!

**Comment by nggvs** [comment]
Hi @HannahBenisty ,

non assigned read appeared in the report as Unclassified, you can calculate the percentage from that. Is there anything that you have found weird?

Thank you!

**Comment by nggvs** [comment]
Are you working with environmental samples? From which environment? Also which pipeline were you using (kraken2 or minimap2?) I'll take a look just in case

**Comment by nggvs** [comment]
Oki, thank you! Also, if you could tell me which version are you using or if you are running a specific parameter I would appreciate it

**Comment by nggvs** [comment]
Hi @HannahBenisty ,
Have you checked the test data to see if you are able to see the unclassified sequences? If that is the case, could you close the issue if you consider the question has been already solved?
Please, open any new issue to provide feedback or to report any issue that you find!
Thank you very much for using the workflow!

**Comment by HannahBenisty** [comment]
Sorry, I did not have time to go back to this issue yet. I will close it and reopen in case I have time to do the test again. Many thanks for your help.
