### ISSUE TITLE
reference table

### ISSUE THREAD

**Issue by HannahBenisty** [epi2me-labs/wf-metagenomics#79]
### Ask away!

Hi, 

I have analyzed my samples using the "minimap2_by_reference" option, specifically for 16S rRNA sequencing. However, I'm uncertain about the specifics of what and how this option measures. Could you provide a detailed description of this option?

Additionally, I would like to know if it's feasible to use this pipeline with FASTQ files generated from PacBio HiFi sequencing, enabling a comparison between the two technologies for the 16S analysis.

Many thanks, 
Hannah

**Comment by cjw85** [comment]
For somewhat obviously reasons we cannot condone the use of this workflow for making comparisons between technologies. 😄 

The option you have reference is described in the documentation as:

> Add a table with the mean sequencing depth per reference, standard deviation and coefficient of variation. It adds a scatterplot of the sequencing depth vs. the coverage and a heatmap showing the depth per percentile to the report
