### ISSUE TITLE
minimap error only when sample sheet is used

### ISSUE THREAD

**Issue by irc47** [epi2me-labs/wf-metagenomics#81]
### Operating System

Windows 11

### Workflow Version

v2.6.1

### Workflow Execution

EPI2ME Desktop application

### EPI2ME Version

v5.1.9

### Workflow Execution - CLI Execution Profile

None

### What happened?

I am running the workflow using minimap2 and attempting to add a sample sheet which I have done successfully in the past. The workflow will complete without the sample sheet. When I include the sheet, it passes sample sheet validation but encounters an error once it gets to the minimap steps: 

ERROR ~ Error executing process > 'minimap_pipeline:minimap (21)'
Caused by: Not a valid path value type: org.codehaus.groovy.runtime.NullObject (null)

Perhaps there is just something wrong with the sample sheet? 
[sample_alias_NP10.csv](https://github.com/epi2me-labs/wf-metagenomics/files/14241621/sample_alias_NP10.csv)

### Relevant log output

```shell
N E X T F L O W  ~  version 23.04.2
Launching `/mnt/c/Users/ilana/epi2melabs/workflows/epi2me-labs/wf-metagenomics/main.nf` [test_with_sample_id] DSL2 - revision: b3b2bd30a2
WARN: NEXTFLOW RECURSION IS A PREVIEW FEATURE - SYNTAX AND FUNCTIONALITY CAN CHANGE IN FUTURE RELEASES
||||||||||   _____ ____ ___ ____  __  __ _____      _       _
||||||||||  | ____|  _ \_ _|___ \|  \/  | ____|    | | __ _| |__  ___
|||||       |  _| | |_) | |  __) | |\/| |  _| _____| |/ _` | '_ \/ __|
|||||       | |___|  __/| | / __/| |  | | |__|_____| | (_| | |_) \__ \
||||||||||  |_____|_|  |___|_____|_|  |_|_____|    |_|\__,_|_.__/|___/
||||||||||  wf-metagenomics v2.6.1
--------------------------------------------------------------------------------
Core Nextflow options
  runName        : test_with_sample_id
  containerEngine: docker
  launchDir      : /mnt/c/Users/ilana/epi2melabs/instances/wf-metagenomics_01HPF2K27WNVZ5GSHAWMX2BQDD
  workDir        : /mnt/c/Users/ilana/epi2melabs/instances/wf-metagenomics_01HPF2K27WNVZ5GSHAWMX2BQDD/work
  projectDir     : /mnt/c/Users/ilana/epi2melabs/workflows/epi2me-labs/wf-metagenomics
  userName       : epi2mewsl
  profile        : standard
  configFiles    : /mnt/c/Users/ilana/epi2melabs/workflows/epi2me-labs/wf-metagenomics/nextflow.config
Input Options
  fastq          : /mnt/c/Users/ilana/Documents/Science/Lab_Work/DNA_Sequencing/Nanopore/NP10_1117/basecalling/pass
  classifier     : minimap2
Sample Options
  sample_sheet   : /mnt/c/Users/ilana/Documents/Science/Lab_Work/Lab Projects/1117- syncom pilot 2023/sample_alias_NP10.csv
Reference Options
  store_dir      : /mnt/c/Users/ilana/epi2melabs/data
  database_sets  : [ncbi_16s_18s:[reference:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s/ncbi_targeted_loci_16s_18s.fna, refindex:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s/ncbi_targeted_loci_16s_18s.fna.fai, database:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s/ncbi_targeted_loci_kraken2.tar.gz, kmer_dist:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s/database1000mers.kmer_distrib, ref2taxid:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s/ref2taxid.targloci.tsv, taxonomy:https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump_archive/taxdmp_2023-01-01.zip], ncbi_16s_18s_28s_ITS:[reference:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s_28s_ITS/ncbi_16s_18s_28s_ITS.fna, refindex:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s_28s_ITS/ncbi_16s_18s_28s_ITS.fna.fai, database:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s_28s_ITS/ncbi_16s_18s_28s_ITS_kraken2.tar.gz, kmer_dist:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s_28s_ITS/database1000mers.kmer_distrib, ref2taxid:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s_28s_ITS/ref2taxid.ncbi_16s_18s_28s_ITS.tsv, taxonomy:https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump_archive/taxdmp_2023-01-01.zip], SILVA_138_1:[database:null], PlusPF-8:[database:https://genome-idx.s3.amazonaws.com/kraken/k2_pluspf_08gb_20230314.tar.gz, taxonomy:https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump_archive/new_taxdump_2023-03-01.zip], PlusPFP-8:[database:https://genome-idx.s3.amazonaws.com/kraken/k2_pluspfp_08gb_20230314.tar.gz, taxonomy:https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump_archive/new_taxdump_2023-03-01.zip]]
Output Options
  out_dir        : /mnt/c/Users/ilana/epi2melabs/instances/wf-metagenomics_01HPF2K27WNVZ5GSHAWMX2BQDD/output
!! Only displaying parameters that differ from the pipeline defaults !!
--------------------------------------------------------------------------------
If you use epi2me-labs/wf-metagenomics for your analysis please cite:
* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x
--------------------------------------------------------------------------------
This is epi2me-labs/wf-metagenomics v2.6.1.
--------------------------------------------------------------------------------
Checking inputs.
Checking fastq input.
[70/c10c40] Submitted process > minimap_pipeline:run_common:getParams
[c3/32eadc] Submitted process > minimap_pipeline:run_common:getVersions
[c7/7fb473] Submitted process > validate_sample_sheet
[4a/6c8892] Submitted process > minimap_pipeline:output (1)
Staging foreign file: https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump_archive/taxdmp_2023-01-01.zip
Staging foreign file: https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s/ncbi_targeted_loci_16s_18s.fna
[05/74f0d2] Submitted process > minimap_pipeline:output (2)
[2d/47cd08] Submitted process > minimap_pipeline:unpackTaxonomy
[a2/64a9fa] Submitted process > minimap_pipeline:check_reference_ref2taxid
WARN: Input directory 'barcode24' was found, but sample sheet '/mnt/c/Users/ilana/Documents/Science/Lab_Work/Lab Projects/1117- syncom pilot 2023/sample_alias_NP10.csv' has no such entry.
[90/877d01] Submitted process > fastcat (11)
[73/f350ea] Submitted process > fastcat (3)
[a2/fb7acb] Submitted process > fastcat (4)
[a9/edd293] Submitted process > fastcat (10)
[d6/e97eb8] Submitted process > minimap_pipeline:minimap (2)
[74/f6c040] Submitted process > fastcat (1)
[ad/309b35] Submitted process > fastcat (8)
[84/301afb] Submitted process > fastcat (2)
[17/b6adee] Submitted process > fastcat (12)
[f9/59bc4f] Submitted process > fastcat (9)
[67/8e3641] Submitted process > fastcat (6)
[7b/189f4c] Submitted process > fastcat (5)
[1a/36ebd8] Submitted process > fastcat (7)
[52/cae4ab] Submitted process > fastcat (13)
[f4/eeac8c] Submitted process > fastcat (15)
[39/77ba56] Submitted process > fastcat (14)
[d4/15599e] Submitted process > fastcat (16)
[8a/96252b] Submitted process > fastcat (17)
[93/21bfb4] Submitted process > fastcat (20)
[6e/97df50] Submitted process > fastcat (19)
[52/c910a1] Submitted process > fastcat (18)
[3a/aecd78] Submitted process > minimap_pipeline:minimap (1)
[a5/674bdd] Submitted process > minimap_pipeline:minimap (3)
ERROR ~ Error executing process > 'minimap_pipeline:minimap (21)'
Caused by:
  Not a valid path value type: org.codehaus.groovy.runtime.NullObject (null)
Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
 -- Check '/mnt/c/Users/ilana/epi2melabs/instances/wf-metagenomics_01HPF2K27WNVZ5GSHAWMX2BQDD/nextflow.log' file for details
[79/e5d65d] Submitted process > minimap_pipeline:minimap (4)
WARN: Killing running tasks (4)
```

### Were you able to successfully run the latest version of the workflow with the demo data?

other (please describe below)

### Other demo data information

```shell
Did not try but I did confirm that it works on my data without the sample sheet
```

**Comment by nggvs** [comment]
Hi @irc47 ,
First of all, thank you for using the workflow! I'll take a look in your issue, thank you for clarifying that it works without the sample_sheet.
I've realised that you are using a previous version of the workflow, is there any reason for that?

Thank you very much in advance

**Comment by irc47** [comment]
Hi Natalia,
Thank you - I didn't realize that I was using a previous version but I now see that an update is available. I will update and retry.
-Ilana

From: Natalia Garcia Garcia ***@***.***>
Sent: Saturday, February 17, 2024 2:51 PM
To: epi2me-labs/wf-metagenomics ***@***.***>
Cc: Ilana Cohen ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL]Re: [epi2me-labs/wf-metagenomics] minimap error only when sample sheet is used (Issue #81)

***ATTENTION: This email came from an external source. Do not open attachments or click on links from unknown senders or unexpected emails.***


Hi @irc47<https://github.com/irc47> ,
First of all, thank you for using the workflow! I'll take a look in your issue, thank you for clarifying that it works without the sample_sheet.
I've realised that you are using a previous version of the workflow, is there any reason for that?

Thank you very much in advance

-

**Comment by nggvs** [comment]
Hi @irc47 ,
Thank you for retrying with the new version, please let me know if that fixes it or let me know if you are still experiencing the same issue.

**Comment by irc47** [comment]
Hi Natalia,
Thank you for checking in - I have updated both Epi2me Labs and the metagenomics workflow but I am still having the same issue (now with a different data set). The workflow completes with the files only but ends with an error when I add a sample sheet. I've attached my most recent log file, the report from that run and the sample sheet that I was using.
Thank you for looking into this!
-Ilana

From: Natalia Garcia Garcia ***@***.***>
Sent: Saturday, February 24, 2024 5:39 AM
To: epi2me-labs/wf-metagenomics ***@***.***>
Cc: Ilana Cohen ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL]Re: [epi2me-labs/wf-metagenomics] minimap error only when sample sheet is used (Issue #81)

***ATTENTION: This email came from an external source. Do not open attachments or click on links from unknown senders or unexpected emails.***


Hi @irc47<https://github.com/irc47> ,
Thank you for retrying with the new version, please let me know if that fixes it or let me know if you are still experiencing the same issue.

-

**Comment by nggvs** [comment]
Hi @irc47 ,
Apologies for the late answer, are you still having this issue?

**Comment by irc47** [comment]
Thanks for checking in – no this issue seems to have gone away. I’m not sure what solved it.
-Ilana

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Natalia Garcia Garcia ***@***.***>
Sent: Thursday, June 6, 2024 8:20:55 AM
To: epi2me-labs/wf-metagenomics ***@***.***>
Cc: Ilana Cohen ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL]Re: [epi2me-labs/wf-metagenomics] minimap error only when sample sheet is used (Issue #81)

***ATTENTION: This email came from an external source. Do not open attachments or click on links from unknown senders or unexpected emails.***


Hi @irc47<https://github.com/irc47> ,
Apologies for the late answer, are you still having this issue?

**Comment by nggvs** [comment]
Glad to hear that! Thank you for using the workflow! I'll close the issue in that case
