### ISSUE TITLE
Is it possible to use EuPathDB46 as a db?

### ISSUE THREAD

**Issue by msubirana** [epi2me-labs/wf-metagenomics#86]
Can EuPathDB46, as listed on https://benlangmead.github.io/aws-indexes/k2, be utilized as a database for the pipeline?

**Comment by nggvs** [comment]
Hi @msubirana ,
Should be possible to use it! Please let me know how are you running the workflow (command line or in the app or other (describe)) and I'll provide some assistance on how to use it.
Thank you very much for using the pipeline!

**Comment by nggvs** [comment]
Hi @msubirana ,
In that case you can use:
```
nextflow run wf-metagenomics/main.nf --fastq path/to/your/data --database https://genome-idx.s3.amazonaws.com/kraken/k2_eupathdb48_20230407.tar.gz.
```
Please check the results to make sure they make sense.
Thank you very much for using the workflow

**Comment by nggvs** [comment]
Hi @msubirana ,
Were you able to run the workflow using that database? If the answer is yes, would you mind to close the issue?
Thank you very much in advance,
Natalia

**Comment by msubirana** [comment]
Hi Natalia,

Thank you for your response, and please accept my apologies for replying late. I haven't had the chance to try it yet but plan to do so next week. Additionally, I have a question regarding the feasibility of combining EuPathDB46 with PlusPF-8 (or PlusPF-16) and running them in the nextflow pipeline.

**Comment by nggvs** [comment]
Hi @msubirana ,
You can combine them outside the workflow to create a new database but you should take a look on kraken2 instructions to create a database and add sequences to them as the one that we offer are pre-built. I think they have a file (library) which includes the sequences IDs to do it. Once you create the database, you can provide it to the workflow using the [custom database](https://labs.epi2me.io/how-to-meta-offline/) option. 

Thank you very much for using the workflow! Also, if you don't mind to close the issue if you consider it has already solved, I would appreciate it.
