### ISSUE TITLE
Trims off adapter sequences

### ISSUE THREAD

**Issue by aimirza** [epi2me-labs/wf-metagenomics#87]
### Is your feature related to a problem?

Hi, the current pipeline does not remove adapter sequences. 

### Describe the solution you'd like

 Would you be able to add a step that removes adapter sequences? 

### Describe alternatives you've considered

You could trim off adapter sequences via porechop_ABI, for example.

**Comment by nggvs** [comment]
Hi @aimirza ,
I have checked this again. Dorado basecalling is trimming the adapters [per default](https://github.com/nanoporetech/dorado/tree/master?tab=readme-ov-file#dna-adapter-and-primer-trimming), so you can use that input in wf-meta
Thank you for using the workflow!
