### ISSUE TITLE
Color Selection for Bar Charts

### ISSUE THREAD

**Issue by irc47** [epi2me-labs/wf-metagenomics#88]
### Ask away!

Does anyone know if it is possible to designate which colors will be assigned to which taxa in the bar charts produced in the wf-metagenomics report? I want to run multiple analyses but keep the color assignments consistent between the runs.

**Comment by nggvs** [comment]
Hi @irc47 ,

At this moment that is not possible, but I agree it would be a nice feature to have. We investigate the case and may consider it for future releases. Thank you for using the workflow!

**Comment by irc47** [comment]
Hi Natalia,
Thank you for following up! Yes, in case it's helpful in the process, the specific case I'd use it would be for having matched colors between runs where the dominant taxa are different.

On another note, if you don't mind, I'm trying to use the exclude_host genome feature, and I'm finding that it doesn't change the output at all, even when I use as an "host" the FASTA for the 16s of the dominant microbe in my sample (I just tried that because I thought the result should be easy to see). Can you point me towards any trouble-shooting resources for this aspect of the workflow?

Thanks,
Ilana

From: Natalia Garcia Garcia ***@***.***>
Sent: Monday, March 25, 2024 6:31 AM
To: epi2me-labs/wf-metagenomics ***@***.***>
Cc: Ilana Cohen ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL]Re: [epi2me-labs/wf-metagenomics] Color Selection for Bar Charts (Issue #88)

***ATTENTION: This email came from an external source. Do not open attachments or click on links from unknown senders or unexpected emails.***


Hi @irc47<https://github.com/irc47> ,

At this moment that is not possible, but I agree it would be a nice feature to have. We investigate the case and may consider it for future releases. Thank you for using the workflow!

-

**Comment by nggvs** [comment]
Hi @irc47 ,
Apologies for the late answer and thanks for using the workflow! Would you mind to open a new issue for this as it seems to be a different issue. It helps us to keep track on the issues.
Thank you very much in advance!
