### ISSUE TITLE
nextflow run on the cloned wf-metagenomics repository on the local system gives an error

### ISSUE THREAD

**Issue by mdrishti** [epi2me-labs/wf-metagenomics#9]
Hi,

I am running nextflow on a server that does not allow communication with github repositories over internet. So, I cloned the wf-metagenomics repository locally. I ran the following command: `nexflow run wf-metagenomics --help`

I got the following error:
`N E X T F L O W  ~  version 19.01.0
Launching wf-metagenomics/main.nf [sick_heyrovsky] - revision: 710763a58e
ERROR ~ The current scope already contains a variable of the name it
 @ line 421, column 33.
               reads.stats.flatMap { it -> [ it[1] ] }.collect(),
                                   ^

_nf_script_9e204e56: 422: The current scope already contains a variable of the name it
 @ line 422, column 30.
               lineages.flatMap { it -> [ it[1] ] }.collect(),
                                ^

_nf_script_9e204e56: 430: The current scope already contains a variable of the name it
 @ line 430, column 30.
                   chan.flatMap { it -> [ it[1] ] }},
                                ^

3 errors
`

I see that these lines are in the main.nf file. I am super new to nextflow and epi2me. Never worked with groovy. Could you please guide me towards figuring out this bug?

Update: I just tried running on a different server that has access to internet through `nextflow run epi2me-labs/wf-metagenomics --help`. It still gives the same error.  

Regards,
D

**Comment by sarahjeeeze** [comment]
Hi, it may be worth updating your Nextflow version with `nextflow self-update` and trying again. It should be 21+ and yours is 19.01.0

**Comment by nggvs** [comment]
Hi,
Thank you for using the workflow. Could you confirm if this issue has been solved? We'll close this ticket on the assumption things are now resolved.
