### ISSUE TITLE
Proxy setting

### ISSUE THREAD

**Issue by anditg** [epi2me-labs/wf-metagenomics#90]
### Ask away!

HI wf-metagenomics Team
Thanks for the great project. I've been using it for a while now to analyse all kinds of sequencing projects. Recently got a new Linux machine and cannot get it to work on that. Behind a firewall. Together with our IT guy we set certificates and proxies in a way that nextflow, java and docker all work. However, when I try to call wf- metagenomics it always gets stuck at "unpacking kraken2 indexes". I believe it can somehow not download the databases correctly. The website is not blocked, I can access it with wget for example. Would you have an idea on how to get this to work?
Thanks in advance

**Comment by nggvs** [comment]
Hi @anditg ,
Thank you for using the workflow! Could you send us the logs of the error you are getting?
Thank you very much!

**Comment by nggvs** [comment]
Hi @anditg ,
Have you been able to run the workflow?
Thank you very much!

**Comment by nggvs** [comment]
Thank you very much! Hope you manage to get it sorted!
Warmly welcome to open new issues!
