### ISSUE TITLE
Error running wf with different Kraken database

### ISSUE THREAD

**Issue by mishkb** [epi2me-labs/wf-metagenomics#94]
### Ask away!

Hi, 
I am trying to run `wf-metagenomics` through EPI2ME using the most recent Kraken2 database for PlusPFP-8 (from https://benlangmead.github.io/aws-indexes/k2). The database works well when I run it through Kraken outside of EPI2ME. And I am able to run `wf-metagenomics` with the built in PlusPFP-8. When I try to run it against the updated database Kraken2 seems to run OK, then there is an issue with Bracken and I am getting an error, as shown in the extracted log below, :

Apr.-22 17:05:43.430 [Actor Thread 7] DEBUG nextflow.Session - Session aborted -- Cause: Process `kraken_pipeline:run_bracken` input file name collision -- There are multiple input files for each of the following file names: Kraken2_pluspfp_08gb_240112

[nextflow.log](https://github.com/epi2me-labs/wf-metagenomics/files/15059015/nextflow.log)

I have attached the nextflow log file. Any ideas on how to resolve? 

Thanks!

**Comment by nggvs** [comment]
Hi @mishkb ,
Thnk you for using the workflow! I'll try to reproduce it. Are you using the app or the command line? Could you paste the command/options you are using?
Thank you very much in advance!

**Comment by mishkb** [comment]
Hi @nggvs ,
Thanks for looking into this. I am using the Epi2Me desktop app (Ubuntu). Via the app, here are the Parameters from the instance that had the error:

{
  classifier: kraken2,
  analyse_unclassified: false,
  real_time: false,
  batch_size: 0,
  port: 8080,
  host: localhost,
  external_kraken2: false,
  server_threads: 2,
  kraken_clients: 2,
  database_set: Standard-8,
  store_dir: /home/nano/epi2melabs/data,
  taxonomic_rank: S,
  kraken2_memory_mapping: false,
  include_kraken2_assignments: false,
  kraken2_confidence: 0,
  minimap2exclude: false,
  split_prefix: false,
  keep_bam: false,
  minimap2_by_reference: false,
  min_percent_identity: 90,
  min_ref_coverage: 0,
  amr: false,
  amr_db: resfinder,
  amr_minid: 80,
  amr_mincov: 80,
  abundance_threshold: 0,
  n_taxa_barplot: 9,
  out_dir: /home/nano/epi2melabs/instances/wf-metagenomics_01HW29TDX684N9MFGB20WF25QH/output,
  min_len: 0,
  threads: 4,
  disable_ping: false,
  help: false,
  version: false,
  fastq: /home/nano/MinION_240419_MAN_WGS/Merged_reads/MAN_N0713,
  database: /home/nano/Kraken2_pluspfp_08gb_240112,
  taxonomy: /home/nano/Kraken2_pluspfp_08gb_240112,
  bracken_length: 300,
  client_fields: /home/nano/epi2melabs/instances/wf-metagenomics_01HW29TDX684N9MFGB20WF25QH/client_fields.json,
  wf: {
    agent: epi2melabs/5.1.10,
    epi2me_instance: 01HW29TDX684N9MFGB20WF25QH,
    epi2me_user: xxx
  }
}

If you need more information, lease let me know!

**Comment by nggvs** [comment]
Thank you! I'll try to reproduce it

**Comment by nggvs** [comment]
Hi @mishkb ,

Which database are you providing as `--taxonomy`. According to your parameters you are providing the same as for kraken2. Taxonomy database is different, the default one uses NCBI taxids. I suspect that the error could be because two databases have the same name and that is why you're getting the input file name collision. 
Could you move the taxonomy database to a different folder or input the folder that contain the nodes.dmp file?

**Comment by mishkb** [comment]
Thanks @nggvs - I have worked that out now. Thanks for the direction re the taxonomy folder.

**Comment by nggvs** [comment]
Glad to hear it has worked!
