### ISSUE TITLE
Classification of ARGs

### ISSUE THREAD

**Issue by lukebsnell** [epi2me-labs/wf-metagenomics#95]
### Is your feature related to a problem?

wf-metagenomics outputs a list of ARGs but does not classify them (e.g. simple beta lacatamase, ESBL, CRO). Currently I have some environmental samples full of ARGs but the detections are difficult to interpret.

### Describe the solution you'd like

It would be useful if the output could classify the genes found, similar to the output of NCBI's AMRFinderPlus. 

### Describe alternatives you've considered

As above.

**Comment by nggvs** [comment]
Hi @lukebsnell ,
Thank you for using the workflow! I take a look on your described suggestions to consider it in future releases!

**Comment by nggvs** [comment]
Hi @lukebsnell ,
I've been taking a look on this. NCBI AMRFinderPlus database is included in the workflow, you would need to use `--amr_db ncbi` or select this database in the app.

Is this the information you'd like to have (if yes would you mind to close the issue?):
![image](https://github.com/epi2me-labs/wf-metagenomics/assets/122800769/b5ba41d0-c60b-4906-9038-2435df592990)
