### ISSUE TITLE
License for epi2me workflow repos

### ISSUE THREAD

**Issue by abhimalatpure** [epi2me-labs/wf-metagenomics#96]
### Ask away!

Hi @SamStudio8.

I am reaching out to you in hopes of figuring out a peculiar issue regarding Oxford nanopore downstream analysis – 
 
Eli Lilly owns a handful of sequencers from Oxford Nanopore (https://nanoporetech.com/). Our team is looking to use Nanopore’s workflows (https://github.com/epi2me-labs) for processing the outputs from the sequencers. I'm trying to find out if the sequencer purchase agreement covers the use of Nanopore's workflows listed under this repo - https://github.com/epi2me-labs.

Are you able to confirm, or point me to a contact at Nanopore who can? Thank you for your help.

Abhi Malatpure
malatpure_abhijeet@lilly.com

**Comment by cjw85** [comment]
The workflows are provided under the terms of the `LICENSE` file provided in each repository.
