### ISSUE TITLE
Angling lables on total read count bar chart

### ISSUE THREAD

**Issue by irc47** [epi2me-labs/wf-metagenomics#97]
### Is your feature related to a problem?

When I use more than a few samples in the workflow, the labels on the raw reads bar chart overlap. 
![image](https://github.com/epi2me-labs/wf-metagenomics/assets/159809201/e3420115-44e9-4f90-bdf4-4bffa5556640)

### Describe the solution you'd like

In the relative abundance barchart, the labels are angled. Can this happen for the raw reads as well? 

![image](https://github.com/epi2me-labs/wf-metagenomics/assets/159809201/062beb60-d224-4682-bd04-99fcbb2207ac)

### Describe alternatives you've considered

It would also be nice to be able to selectively hide bars while looking at these charts. That would be an additional feature but would also resolve this issue.

**Comment by nggvs** [comment]
Hi @irc47 ,
Thanks for using the workflow! I take note of this and try to solve it in the next release!

**Comment by nggvs** [comment]
Hi @irc47 ,
This change is already in pre-release and should be released in the next weeks. I'll let you know once the new version is released!
Thank you for using the workflow! and please let me know any other suggestion!

**Comment by irc47** [comment]
Hi Natalia,
Thanks for the update, I look forward to trying the new release.  My other suggestion would be that it would great to be able to provide metadata in the sample sheet and then to sort the samples (especially in the relative abundance bar chart) by those metadata.
-Ilana
From: Natalia Garcia Garcia ***@***.***>
Sent: Wednesday, May 29, 2024 6:29 AM
To: epi2me-labs/wf-metagenomics ***@***.***>
Cc: Ilana Cohen ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL]Re: [epi2me-labs/wf-metagenomics] Angling lables on total read count bar chart (Issue #97)

***ATTENTION: This email came from an external source. Do not open attachments or click on links from unknown senders or unexpected emails.***


Hi @irc47<https://github.com/irc47> ,
This change is already in pre-release and should be released in the next weeks. I'll let you know once the new version is released!
Thank you for using the workflow! and please let me know any other suggestion!

-

**Comment by nggvs** [comment]
Hi @irc47 ,
I take note on your suggestions for future releases :)
Thank you very much for your feedback!
