### ISSUE TITLE
AMR 

### ISSUE THREAD

**Issue by SilSanGon** [epi2me-labs/wf-metagenomics#99]
### Is your feature related to a problem?

Hello,
We are starting with the study of resistance genes, and we are using EPI2ME Desktop and we were very happy because it provided a lot of information very useful. However, if we comparing EPI2ME Agent vs EPI2ME Desktop, EPI2ME Agent analysis Fastq Antimicrobial Resistance showed the taxon to which the resistance gene belongs and the ontology of the resistance gene, but we can see that this option isn’t in EPI2ME Desktop wf-metagenomics. Is it planned to have these options a nearer future, please? Could it be downloaded as a table and not as a json, please?

We are looking forward to hearing from you.

Thank you!

### Describe the solution you'd like

EPI2ME Desktop wf-metagenomics displays the taxon to which the resistance gene belongs and the ontology of the resistance gene, as provided by the EPI2ME Agent, and downloads as csv, tsv or txt, but not as a .json.

### Describe alternatives you've considered

Information on the taxon to which the resistance gene belongs and the ontology of the resistance gene could be provided in a separate table as general, not only that found in our samples.

**Comment by nggvs** [comment]
Hi @SilSanGon ,
Thanks for your suggestion and for using the workflow!
I think there is another one related to AMR, we consider that for future releases. So you would like to have a table with the AMR gene and the taxon? Could you provide an example? Also would be nice if you briefly describe why this can be useful for you to consider other user cases.

Thank you very much!

**Comment by SilSanGon** [comment]
Hi @nggvs,
What is the other AMR-related workflow you said above, please? 
I attach a report of EPI2ME Agent with the table of AMR genes and  taxonomy ontology as an example of table:
[Fastq Antimicrobial Resistance [Instance ID_ 452053].pdf](https://github.com/user-attachments/files/15530892/Fastq.Antimicrobial.Resistance.Instance.ID_.452053.pdf)
In my case I think it is useful to research AMR genes to identificate or to comparison of ARGs host identification as Wu et al., 2022 does (https://doi.org/10.1016/j.watres.2022.119282.).

Thank you very much!

**Comment by nggvs** [comment]
Hi @SilSanGon ,
Thank you very much for the outputs! I'll take a look!. The issue I was referring to is this one: https://github.com/epi2me-labs/wf-metagenomics/issues/95, is also related with your suggestion?

Thank you very much in advance!

**Comment by nggvs** [comment]
Hi @SilSanGon 
I'll be reviewing very soon the amr feature attending to the user's feedback :) So, I'm going to close this meanwhile. Hopefully you find this implemented in the future releases.
Thank you very much in advance for the feedback!
